kkkkkkkobzillla-utils: org.cobbzilla.util.io.FilesystemWalker.FsWalker.run
run()
void org.cobbzilla.util.io.FilesystemWalker.FsWalker.run ()
Definition at line 87 of file FilesystemWalker.java.
References org.cobbzilla.util.io.FilesystemWalker.fileJob(), org.cobbzilla.util.io.FilesystemWalker.hasFilter(), and org.cobbzilla.util.io.FilesystemWalker.FsWalker.visit().
{
             if (isSymlink(file) && !includeSymlinks) return;
             if (file.isFile()) {
                 // visit the file
                 visit();
             } else if (file.isDirectory()) {
                 // should we visit directory entries?
                 if (visitDirs) visit();
                 // should we filter directory entries?
                 final File[] files = hasFilter() ? file.listFiles(filter) : file.listFiles();
                 // walk each entry in the directory
                 if (files != null) for (File f : files) fileJob(f);
             } else {
                 log.warn("unexpected file: neither file nor directory, skipping: "+abs(file));
             }
         }