kkkkkkkobzillla-utils: org.cobbzilla.util.dns.DnsRecordBase.match
match()
boolean org.cobbzilla.util.dns.DnsRecordBase.match (DnsRecordMatch match)
Definition at line 28 of file DnsRecordBase.java.
References org.cobbzilla.util.dns.DnsRecordBase.getNormalFqdn(), org.cobbzilla.util.dns.DnsRecordBase.hasFqdn(), org.cobbzilla.util.dns.DnsRecordMatch.hasSubdomain(), org.cobbzilla.util.dns.DnsRecordBase.hasType(), org.cobbzilla.util.dns.DnsRecordBase.hasValue(), and org.cobbzilla.util.dns.DnsRecordBase.value.
{
         // strip trailing dot if there is one
         final String val = !hasValue() || !value.endsWith(".") ? value : chop(value);
         if (match.hasSubdomain() && !getNormalFqdn().endsWith(match.getSubdomain())) return false;
         if (match.hasType() && getType() != match.getType()) return false;
         if (match.hasFqdn() && !getNormalFqdn().equalsIgnoreCase(match.getFqdn())) return false;
         if (match.hasValue() && hasValue() && !val.equalsIgnoreCase(match.getValue())) return false;
         return true;
     }