kkkkkkkobzillla-utils: org.cobbzilla.util.json.JsonUtilTest.jsonObjectEquals
jsonObjectEquals()
boolean org.cobbzilla.util.json.JsonUtilTest.jsonObjectEquals (ObjectNode n1, ObjectNode n2) private
Definition at line 93 of file JsonUtilTest.java.
References org.cobbzilla.util.json.JsonUtilTest.jsonEquals(), and org.cobbzilla.util.json.JsonUtilTest.toMap().
Referenced by org.cobbzilla.util.json.JsonUtilTest.jsonEquals().
{
         final Map<String, JsonNode> n1fields = toMap(n1);
         final Map<String, JsonNode> n2fields = toMap(n2);
         if (n1fields.size() != n2fields.size()) return false;
         for (Map.Entry<String, JsonNode> n1entry : n1fields.entrySet()) {
             if (!jsonEquals(n1entry.getValue(), n2fields.get(n1entry.getKey()))) return false;
         }
         return true;
     }