kkkkkkkobzillla-utils: org.cobbzilla.util.xml.XmlUtil.findLargest
findLargest()
static <T> T org.cobbzilla.util.xml.XmlUtil.findLargest (Document doc, final ElementMatcher matcher, final ElementTransformer< T > transformer) static
Definition at line 162 of file XmlUtil.java.
References org.cobbzilla.util.xml.XmlUtil.applyRecursively(), org.cobbzilla.util.xml.ElementMatcher.matches(), and org.cobbzilla.util.xml.ElementTransformer< T >.transform().
{
         final AtomicReference<T> largest = new AtomicReference<>();
         applyRecursively(doc.getDocumentElement(), element -> {
             if (matcher.matches(element)) {
                 final T val = transformer.transform(element);
                 if (val != null) {
                     synchronized (largest) {
                         final T curVal = largest.get();
                         if (curVal == null || ((Comparable) val).compareTo(curVal) > 0) largest.set(val);
                     }
                 }
             }
         });
         return largest.get();
     }