kkkkkkkobzillla-utils: org.cobbzilla.util.xml.XmlUtil.applyRecursively
applyRecursively()
static Node org.cobbzilla.util.xml.XmlUtil.applyRecursively (Element element, XmlElementFunction func) static
Definition at line 97 of file XmlUtil.java.
References org.cobbzilla.util.xml.XmlElementFunction.apply().
Referenced by org.cobbzilla.util.xml.XmlUtil.findElements(), org.cobbzilla.util.xml.XmlUtil.findLargest(), and org.cobbzilla.util.xml.XmlUtil.getElementById().
{
         func.apply(element);
         final NodeList childNodes = element.getChildNodes();
         if (childNodes != null && childNodes.getLength() > 0) {
             for (int i = 0; i < childNodes.getLength(); i++) {
                 final Node item = childNodes.item(i);
                 if (item instanceof Element) applyRecursively((Element) item, func);
             }
         }
         return element;
     }