kkkkkkkobzillla-utils: org.cobbzilla.util.collection.multi.MultiResultDriverBase.exec
exec()
void org.cobbzilla.util.collection.multi.MultiResultDriverBase.exec (Object task)
Implements org.cobbzilla.util.collection.multi.MultiResultDriver.
Definition at line 17 of file MultiResultDriverBase.java.
References org.cobbzilla.util.collection.multi.MultiResultDriverBase.after(), org.cobbzilla.util.collection.multi.MultiResultDriverBase.before(), org.cobbzilla.util.collection.multi.MultiResultDriverBase.failure(), org.cobbzilla.util.collection.multi.MultiResultDriverBase.failureMessage(), org.cobbzilla.util.collection.multi.MultiResultDriverBase.run(), org.cobbzilla.util.collection.multi.MultiResultDriverBase.success(), and org.cobbzilla.util.collection.multi.MultiResultDriverBase.successMessage().
{
         try {
             before();
             run(task);
             success(successMessage(task));
         } catch (Exception e) {
             failure(failureMessage(task), e);
         } finally {
             after();
         }
     }