kkkkkkkobzillla-utils: org.cobbzilla.util.json.JsonUtil.fromJsonOrDie
fromJsonOrDie() [1/6]
static <T> T org.cobbzilla.util.json.JsonUtil.fromJsonOrDie (File json, Class< T > clazz) static
Definition at line 193 of file JsonUtil.java.
References org.cobbzilla.util.io.FileUtil.toStringOrDie().
Referenced by org.cobbzilla.util.json.JsonUtil.fromJsonOrDie(), org.cobbzilla.util.http.HttpResponseBean.getEntity(), org.cobbzilla.util.json.JsonUtil.json(), org.cobbzilla.util.json.JsonUtil.jsonWithComments(), org.cobbzilla.util.json.JsonUtil.nodeValue(), and org.cobbzilla.util.json.JsonUtil.toNode().
{
         return fromJsonOrDie(FileUtil.toStringOrDie(json), clazz);
     }