kkkkkkkobzillla-utils: org.cobbzilla.util.json.JsonUtil.findNode
findNode()
static JsonNode org.cobbzilla.util.json.JsonUtil.findNode (JsonNode node, String path) throws IOException static
Definition at line 260 of file JsonUtil.java.
References org.cobbzilla.util.json.JsonUtil.findNodePath().
Referenced by org.cobbzilla.util.json.JsonUtil.fromJson(), and org.cobbzilla.util.json.JsonUtil.nodeValue().
{
         if (node == null) return null;
         final List<JsonNode> nodePath = findNodePath(node, path);
         if (nodePath == null || nodePath.isEmpty()) return null;
         final JsonNode lastNode = nodePath.get(nodePath.size()-1);
         return lastNode == MISSING ? null : lastNode;
     }