kkkkkkkobzillla-utils: org.cobbzilla.util.json.JsonUtil.findNodePath
findNodePath()
static List<JsonNode> org.cobbzilla.util.json.JsonUtil.findNodePath (JsonNode node, String path) throws IOException static
Definition at line 276 of file JsonUtil.java.
References org.cobbzilla.util.json.JsonUtil.tokenize().
Referenced by org.cobbzilla.util.json.JsonUtil.findNode(), and org.cobbzilla.util.json.JsonUtil.replaceNode().
{
         final List<JsonNode> nodePath = new ArrayList<>();
         nodePath.add(node);
         if (empty(path)) return nodePath;
         final List<String> pathParts = tokenize(path);
         for (String pathPart : pathParts) {
             int index = -1;
             int bracketPos = pathPart.indexOf("[");
             int bracketClosePos = pathPart.indexOf("]");
             boolean isEmptyBrackets = false;
             if (bracketPos != -1 && bracketClosePos != -1 && bracketClosePos > bracketPos) {
                 if (bracketClosePos == bracketPos+1) {
                     // ends with [], they mean to append
                     isEmptyBrackets = true;
                 } else {
                     index = Integer.parseInt(pathPart.substring(bracketPos + 1, bracketClosePos));
                 }
                 pathPart = pathPart.substring(0, bracketPos);
             }
             if (!empty(pathPart)) {
                 node = node.get(pathPart);
                 if (node == null) {
                     nodePath.add(MISSING);
                     return nodePath;
                 }
                 nodePath.add(node);
             } else if (nodePath.size() > 1) {
                 return die("findNodePath: invalid path: "+path);
             }
             if (index != -1) {
                 node = node.get(index);
                 nodePath.add(node);
             } else if (isEmptyBrackets) {
                 nodePath.add(MISSING);
                 return nodePath;
             }
         }
         return nodePath;
     }