kkkkkkkobzillla-utils: org.cobbzilla.util.json.JsonUtil.mergeJsonNodes
mergeJsonNodes()
static JsonNode org.cobbzilla.util.json.JsonUtil.mergeJsonNodes (String json, Object request) throws Exception static
Definition at line 475 of file JsonUtil.java.
References org.cobbzilla.util.json.JsonUtil.fromJson(), org.cobbzilla.util.json.JsonUtil.json(), and org.cobbzilla.util.json.JsonUtil.mergeNodes().
Referenced by org.cobbzilla.util.json.JsonUtil.mergeJson(), and org.cobbzilla.util.json.JsonUtil.mergeJsonNodesOrDie().
{
         if (request != null) {
             if (json != null) {
                 final JsonNode current = fromJson(json, JsonNode.class);
                 final JsonNode update;
                 if (request instanceof JsonNode) {
                     update = (JsonNode) request;
                 } else {
                     update = PUBLIC_MAPPER.valueToTree(request);
                 }
                 mergeNodes(current, update);
                 return current;
             } else {
                 return PUBLIC_MAPPER.valueToTree(request);
             }
         }
         return json(json, JsonNode.class);
     }