kkkkkkkobzillla-utils: org.cobbzilla.util.io.FilesystemWalker.walk
walk()
AwaitResult org.cobbzilla.util.io.FilesystemWalker.walk ()
Definition at line 51 of file FilesystemWalker.java.
References org.cobbzilla.util.io.FilesystemWalker.awaitFutures(), org.cobbzilla.util.io.FilesystemWalker.fileJob(), and org.cobbzilla.util.io.FilesystemWalker.numFutures().
Referenced by org.cobbzilla.util.io.main.UniqueFileWalkerMain.run().
{
         for (File dir : dirs) fileJob(dir);
         // wait for number of futures to stop increasing
         do {
             final int lastNumFutures = numFutures();
             awaitFutures();
             if (numFutures() == lastNumFutures) break;
             sleep(getSleepTime());
         } while (true);
         return awaitFutures();
     }