kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtilTest.testGetSet
testGetSet()
void org.cobbzilla.util.reflect.ReflectionUtilTest.testGetSet () throws Exception
Definition at line 33 of file ReflectionUtilTest.java.
References org.cobbzilla.util.reflect.ReflectionUtil.get(), org.cobbzilla.util.reflect.ReflectionUtil.set(), and org.cobbzilla.util.reflect.ReflectionUtil.setNull().
{
         Long testValue = now();
         Dummy dummy = new Dummy(testValue, NAME);
         assertEquals(ReflectionUtil.get(dummy, ID), testValue);
         ReflectionUtil.set(dummy, ID, null);
         assertNull(ReflectionUtil.get(dummy, ID));
         testValue += 10;
         ReflectionUtil.set(dummy, ID, testValue);
         assertEquals(ReflectionUtil.get(dummy, ID), testValue);
         ReflectionUtil.setNull(dummy, ID, Long.class);
         assertNull(ReflectionUtil.get(dummy, ID));
         ReflectionUtil.set(dummy, NAME, "a value");
         assertEquals(ReflectionUtil.get(dummy, NAME), "a value");
         try {
             ReflectionUtil.set(dummy, NAME, null);
             fail("should not have been able to set name field to null");
         } catch (Exception expected) {}
         ReflectionUtil.setNull(dummy, NAME, String.class);
         assertNull(ReflectionUtil.get(dummy, NAME));
     }