kkkkkkkobzillla-utils: org.cobbzilla.util.io.JarTrimmer.shouldInclude
shouldInclude()
boolean org.cobbzilla.util.io.JarTrimmer.shouldInclude (JarTrimmerConfig config, String name) private
Definition at line 105 of file JarTrimmer.java.
References org.cobbzilla.util.io.JarTrimmerConfig.required(), and org.cobbzilla.util.io.JarTrimmer.toPath().
Referenced by org.cobbzilla.util.io.JarTrimmer.trim().
{
         if (name.endsWith("/")) return false;
         if (config.required(name)) return true;
         return counter.getCounter(toPath(name)).getTotalCount() > 0;
     }