kkkkkkkobzillla-utils: org.cobbzilla.util.io.JarTrimmer.trim
trim()
IncludeCount org.cobbzilla.util.io.JarTrimmer.trim (JarTrimmerConfig config) throws Exception
Definition at line 58 of file JarTrimmer.java.
References org.cobbzilla.util.reflect.ReflectionUtil.copy(), org.cobbzilla.util.io.JarTrimmer.counter, org.cobbzilla.util.io.JarTrimmer.processJar(), org.cobbzilla.util.io.FileUtil.renameOrDie(), org.cobbzilla.util.io.JarTrimmer.shouldInclude(), org.cobbzilla.util.io.FileUtil.temp(), and org.cobbzilla.util.io.JarTrimmer.toPath().
Referenced by org.cobbzilla.util.io.main.JarTrimmerMain.run().
{
         final JarFile jar = new JarFile(config.getInJar());
         // walk all class resources in jar file, track location/count of required classes
         processJar(jar, jarEntry -> {
             final String name = jarEntry.getName();
             if (name.endsWith(CLASS_SUFFIX)) {
                 if (config.required(name)) counter.getCounter(toPath(name)).incr();
             }
             return null;
         });
         // Level 1: any packages that do not contain ANY required classes will not be included in the output jar
         final File temp = FileUtil.temp(".jar");
         @Cleanup final JarOutputStream jarOut = new JarOutputStream(new FileOutputStream(temp));
         final Set<String> dirsCreated = new HashSet<>();
         processJar(jar, jarEntry -> {
             final String name = jarEntry.getName();
             if (shouldInclude(config, name)) {
                 try {
                     final String dir = name.contains("/") ? toPath(name) : null;
                     if (dir != null && !dirsCreated.contains(dir)) {
                         final JarEntry dirEntry = new JarEntry(dir +"/");
                         dirEntry.setTime(jarEntry.getTime());
                         jarOut.putNextEntry(dirEntry);
                         dirsCreated.add(dir);
                     }
                     final JarEntry outEntry = new JarEntry(jarEntry.getName());
                     ReflectionUtil.copy(outEntry, jarEntry, new String[] {"method", "time", "size", "compressedSize", "crc"});
                     jarOut.putNextEntry(outEntry);
                     @Cleanup final InputStream in = jar.getInputStream(jarEntry);
                     IOUtils.copy(in, jarOut);
                 } catch (Exception e) {
                     return die("processJar: " + e, e);
                 }
             } else if (!name.endsWith("/")) {
                 log.info("omitted: "+ name);
             }
             return null;
         });
         FileUtil.renameOrDie(temp, config.getOutJar());
         return counter;
     }