kkkkkkkobzillla-utils: org.cobbzilla.util.io.TarballTest.validateUnrolledTarball
validateUnrolledTarball()
void org.cobbzilla.util.io.TarballTest.validateUnrolledTarball (File unrolledDir) throws IOException protected
Definition at line 48 of file TarballTest.java.
References org.cobbzilla.util.security.ShaUtil.sha256(), org.cobbzilla.util.string.StringUtil.tohex(), and org.cobbzilla.util.io.FileUtil.toString().
Referenced by org.cobbzilla.util.io.TarballTest.testUnrollAndReroll().
{
         final File[] files = unrolledDir.listFiles();
         assertEquals(2, files.length);
         int fileIndex, subdirIndex;
         if (files[0].getName().equals("file1.txt")) {
             fileIndex = 0;
             subdirIndex = 1;
         } else {
             subdirIndex = 0;
             fileIndex = 1;
         }
         String shasum;
         assertEquals("file1.txt", files[fileIndex].getName());
         assertEquals(4160, files[fileIndex].length());
         shasum = StringUtil.tohex(ShaUtil.sha256(FileUtil.toString(files[fileIndex])));
         assertEquals("62b74f00961184e2b448adfcf38ee6186d94b15ea6a364917d72645d8705a30c", shasum);
         assertEquals("subdir", files[subdirIndex].getName());
         assertTrue("subdir", files[subdirIndex].isDirectory());
         final File[] subdirFiles = files[subdirIndex].listFiles();
         assertEquals(1, subdirFiles.length);
         assertEquals("subfile.txt", subdirFiles[0].getName());
         assertEquals(65072, subdirFiles[0].length());
         shasum = StringUtil.tohex(ShaUtil.sha256(FileUtil.toString(subdirFiles[0])));
         assertEquals("4ded9b8ff2cb3b94ff0bb15b8e17aff795c7f64bd088d5d70acb38ad286e2d12", shasum);
     }