kkkkkkkobzillla-utils: org.cobbzilla.util.xml.TidyUtil.tidy
tidy() [4/4]
static String org.cobbzilla.util.xml.TidyUtil.tidy (String html, TidyHelper... helpers) static
Definition at line 25 of file TidyUtil.java.
References org.cobbzilla.util.xml.TidyUtil.createTidy(), org.cobbzilla.util.xml.TidyUtil.parse(), and org.cobbzilla.util.xml.TidyUtil.tidy().
{
         try {
             @Cleanup final ByteArrayInputStream in = new ByteArrayInputStream(html.getBytes());
             @Cleanup final ByteArrayOutputStream out = new ByteArrayOutputStream();
             if (empty(helpers)) {
                 parse(in, out, false);
             } else {
                 final Tidy tidy = createTidy();
                 final Document doc = tidy.parseDOM(in, null);
                 for (TidyHelper helper : helpers) {
                     helper.process(doc);
                 }
                 tidy.pprint(doc, out);
             }
             return out.toString();
         } catch (Exception e) {
             return die("tidy: " + e, e);
         }
     }