kkkkkkkobzillla-utils: org.cobbzilla.util.xml.TidyUtil.parse
parse()
static void org.cobbzilla.util.xml.TidyUtil.parse (InputStream in, OutputStream out, boolean removeScripts) static
Definition at line 46 of file TidyUtil.java.
References org.cobbzilla.util.xml.TidyUtil.createTidy(), org.cobbzilla.util.xml.TidyUtil.removeDuplicateAttributes(), org.cobbzilla.util.xml.TidyUtil.removeElement(), and org.cobbzilla.util.xml.TidyUtil.tidy().
Referenced by org.cobbzilla.util.xml.XPathUtil.getDocument(), and org.cobbzilla.util.xml.TidyUtil.tidy().
{
         final Tidy tidy = createTidy();
         if (!removeScripts) {
             tidy.parse(in, out);
         } else {
             final Document doc = tidy.parseDOM(in, null);
             removeElement(doc.getDocumentElement(), "script");
             removeElement(doc.getDocumentElement(), "style");
             removeDuplicateAttributes(doc.getDocumentElement());
             tidy.pprint(doc, out);
         }
     }