kkkkkkkobzillla-utils: org.cobbzilla.util.daemon.SimpleDaemon.stopWithPossibleKill
stopWithPossibleKill()
void org.cobbzilla.util.daemon.SimpleDaemon.stopWithPossibleKill (long wait)
Tries to stop the daemon.
If it doesn't stop within "wait" millis, it gets killed.
Definition at line 80 of file SimpleDaemon.java.
References org.cobbzilla.util.daemon.SimpleDaemon.getIsAlive(), org.cobbzilla.util.daemon.SimpleDaemon.kill(), org.cobbzilla.util.daemon.SimpleDaemon.start(), org.cobbzilla.util.daemon.SimpleDaemon.stop(), and org.cobbzilla.util.daemon.SimpleDaemon.wait().
{
         stop();
         long start = now();
         while (getIsAlive()
                 && (now() - start < wait)) {
             wait(25, "stopWithPossibleKill");
         }
         if (getIsAlive()) {
             kill();
         }
     }