kkkkkkkobzillla-utils: org.cobbzilla.util.daemon.SimpleDaemon.run
run()
void org.cobbzilla.util.daemon.SimpleDaemon.run ()
Definition at line 94 of file SimpleDaemon.java.
References org.cobbzilla.util.daemon.SimpleDaemon.cleanup(), org.cobbzilla.util.daemon.SimpleDaemon.getSleepTime(), org.cobbzilla.util.daemon.SimpleDaemon.getStartupDelay(), org.cobbzilla.util.daemon.SimpleDaemon.init(), org.cobbzilla.util.daemon.SimpleDaemon.onStart(), org.cobbzilla.util.daemon.SimpleDaemon.onStop(), org.cobbzilla.util.daemon.SimpleDaemon.process(), and org.cobbzilla.util.daemon.SimpleDaemon.wait().
                       {
         onStart();
         long delay = getStartupDelay();
         if (delay > 0) {
             log.debug(name + ": Delaying daemon startup for " + delay + "ms...");
             if (!wait(delay, "run[startup-delay]")) return;
         }
         log.debug(name + ": Daemon thread now running");
         try {
             log.debug(name + ": Daemon thread invoking init");
             init();
             while (!isDone) {
                 log.debug(name + ": Daemon thread invoking process");
                 process();
                 lastProcessTime = now();
                 if (isDone) return;
                 if (!wait(getSleepTime(), "run[post-processing]")) return;
             }
         } catch (Exception e) {
             log.error(name + ": Error in daemon, exiting: " + e, e);
         } finally {
             cleanup();
             try {
                 onStop();
             } catch (Exception e) {
                 log.error(name + ": Error in onStop, exiting and ignoring error: " + e, e);
             }
         }
     }