kkkkkkkobzillla-utils: org.cobbzilla.util.io.main.FilesystemWatcherMain.run
run()
void org.cobbzilla.util.io.main.FilesystemWatcherMain.run () throws Exception protected
Definition at line 24 of file FilesystemWatcherMain.java.
References org.cobbzilla.util.main.BaseMainOptions.err(), org.cobbzilla.util.system.CommandShell.exec(), org.cobbzilla.util.io.main.FilesystemWatcherMainOptions.getDamperMillis(), org.cobbzilla.util.io.main.FilesystemWatcherMainOptions.getWatchPaths(), org.cobbzilla.util.io.main.FilesystemWatcherMainOptions.hasCommand(), and org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.options.
{
         final FilesystemWatcherMainOptions options = getOptions();
         final DamperedCompositeBufferedFilesystemWatcher watcher = new DamperedCompositeBufferedFilesystemWatcher
                 (options.getTimeout(), options.getMaxEvents(), options.getWatchPaths(), options.getDamperMillis()) {
             @Override public void uber_fire(List<WatchEvent<?>> events) {
                 try {
                     if (options.hasCommand()) {
                         CommandShell.exec(new CommandLine(options.getCommand()));
                     } else {
                         final String msg = status() + " uber_fire ("+events.size()+" events) at " + DFORMAT.print(now());
                         log.info(msg);
                         System.out.println(msg);
                     }
                 } catch (Exception e) {
                     final String msg = status() + " Error running command (" + options.getCommand() + "): "
                             + e + "\n" + ExceptionUtils.getStackTrace(e);
                     log.error(msg, e);
                     System.err.println(msg);
                 }
             }
         };
         synchronized (watcher) {
             watcher.wait();
         }
     }