kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.print
print()
CharSequence org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.print (DateTimeFormatter formatter, Object src, Options options) protected
Definition at line 606 of file HandlebarsUtil.java.
References org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.getTimeZone(), and org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.zonedTimestamp().
Referenced by org.cobbzilla.util.handlebars.HandlebarsUtil.registerDateHelpers().
{
             return new Handlebars.SafeString(formatter.print(new DateTime(zonedTimestamp(src, options),
                                                                           getTimeZone(options))));
         }