kkkkkkkobzillla-utils: org.cobbzilla.util.system.CommandShell.scriptResult
scriptResult() [4/4]
static CommandResult org.cobbzilla.util.system.CommandShell.scriptResult (String contents, Map< String, String > env, String input, List< Integer > exitValues) static
Definition at line 297 of file CommandShell.java.
References org.cobbzilla.util.system.CommandShell.exec(), org.cobbzilla.util.system.Command.setExitValues(), and org.cobbzilla.util.system.CommandShell.tempScript().
{
         try {
             @Cleanup("delete") final File script = tempScript(contents);
             final Command command = new Command(new CommandLine(script)).setEnv(env).setInput(input);
             if (!empty(exitValues)) command.setExitValues(exitValues);
             return exec(command);
         } catch (Exception e) {
             return die("Error executing: "+e);
         }
     }