kkkkkkkobzillla-utils: org.cobbzilla.util.system.CommandShell.exec
exec() [1/4]
static MultiCommandResult org.cobbzilla.util.system.CommandShell.exec (Collection< String > commands) throws IOException static
Definition at line 134 of file CommandShell.java.
References org.cobbzilla.util.system.MultiCommandResult.add(), and org.cobbzilla.util.system.MultiCommandResult.hasException().
Referenced by org.cobbzilla.util.system.CommandShell.exec(), org.cobbzilla.util.http.HttpUtil.isOk(), org.cobbzilla.util.io.main.FilesystemWatcherMain.run(), org.cobbzilla.util.system.CommandShell.scriptResult(), org.cobbzilla.util.system.CommandShellTest.testProgressFilter(), org.cobbzilla.util.system.CommandShellTest.testStreamCallbacks(), and org.cobbzilla.util.system.CommandShell.toString().
{
         final MultiCommandResult result = new MultiCommandResult();
         for (String c : commands) {
             Command command = new Command(c);
             result.add(command, exec(c));
             if (result.hasException()) return result;
         }
         return result;
     }