kkkkkkkobzillla-utils: org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.mergeSpans
mergeSpans()
void org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.mergeSpans (Node parent, MappyList< Node, Node > toRemove) protected
Definition at line 28 of file TidyHandlebarsSpanMerger.java.
References org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.append(), org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.collectText(), org.cobbzilla.util.collection.mappy.Mappy< K, V, List< V > >.put(), org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.sameAttrs(), and org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.setSpan().
Referenced by org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.process().
{
         Node spanStart = null;
         StringBuilder spanTemp = null;
         NodeList childNodes = parent.getChildNodes();
         for (int i=0; i <childNodes.getLength(); i++) {
             final Node child = childNodes.item(i);
             if (child.getNodeType() == Node.ELEMENT_NODE) {
                 if (child.getNodeName().equalsIgnoreCase("span")) {
                     if (spanStart == null) {
                         spanStart = child;
                         spanTemp = new StringBuilder(collectText(child));
                     } else if (sameAttrs(spanStart.getAttributes(), child.getAttributes())) {
                         //noinspection ConstantConditions
                         append(spanTemp, collectText(child));
                         setSpan(spanStart, spanTemp);
                         toRemove.put(parent, child);
                     } else {
                         spanStart = child;
                         spanTemp = new StringBuilder(collectText(child));
                     }
                 } else if (child.hasChildNodes()) {
                     mergeSpans(child, toRemove);
                 }
                 continue;
             } else if (child.getNodeType() == Node.TEXT_NODE) {
                 if (spanTemp != null) {
                     append(spanTemp, child.getNodeValue());
                     setSpan(spanStart, spanTemp);
                     toRemove.put(parent, child);
                     continue;
                 }
             }
             if (child.hasChildNodes()) {
                 mergeSpans(child, toRemove);
             }
         }
         if (spanStart != null && spanTemp != null && spanTemp.length() > 0) {
             setSpan(spanStart, spanTemp);
         }
     }