kkkkkkkobzillla-utils: org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.scrubHandlebars
scrubHandlebars()
static String org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.scrubHandlebars (String text) static
Definition at line 77 of file TidyHandlebarsSpanMerger.java.
References org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.append(), and org.cobbzilla.util.xml.TidyHandlebarsSpanMerger.scrubHtmlEntities().
Referenced by org.cobbzilla.util.handlebars.WordDocxMerger.merge().
{
         final StringBuilder b = new StringBuilder();
         int start = 0;
         int pos = text.indexOf(HB_START, start);
         while (pos != -1) {
             b.append(text.substring(start, pos)).append(HB_START);
             start = pos + 2;
             int endPos = text.indexOf(HB_END, start);
             if (endPos == -1) {
                 b.append(text.substring(start));
                 return b.toString();
             } else {
                 b.append(scrubHtmlEntities(text.substring(start, endPos))).append(HB_END);
                 start = endPos + 2;
             }
             pos = text.indexOf(HB_START, start);
         }
         if (start != text.length()-1) b.append(text.substring(start));
         return b.toString();
     }