kkkkkkkobzillla-utils: org.cobbzilla.util.time.TimeUtil.startOfMonth
startOfMonth() [1/2]
static DateTime org.cobbzilla.util.time.TimeUtil.startOfMonth () static
Definition at line 147 of file TimeUtil.java.
References org.cobbzilla.util.time.TimeUtil.startOfMonth().
Referenced by org.cobbzilla.util.time.TimeUtil.startOfMonth(), and org.cobbzilla.util.time.TimeUtil.startOfMonthMillis().
 { return startOfMonth(DefaultTimezone.getZone()); }