kkkkkkkobzillla-utils: org.cobbzilla.util.cron.quartz.QuartzMaster.addJob
addJob()
void org.cobbzilla.util.cron.quartz.QuartzMaster.addJob (final CronJob job) throws SchedulerException
Implements org.cobbzilla.util.cron.CronDaemon.
Definition at line 41 of file QuartzMaster.java.
References org.cobbzilla.util.cron.CronCommand.exec(), and org.cobbzilla.util.cron.CronCommand.init().
Referenced by org.cobbzilla.util.cron.quartz.QuartzMaster.start().
{
         String id = job.getId();
         Job specialJob = new Job () {
             @Override
             public void execute(JobExecutionContext context) throws JobExecutionException {
                 Map<String, Object> map = context.getMergedJobDataMap();
                 try {
                     CronCommand command = job.getCommandInstance();
                     command.init(job.getProperties());
                     command.exec(map);
                 } catch (Exception e) {
                     throw new JobExecutionException(e);
                 }
             }
         };
         final JobDetail jobDetail = newJob(specialJob.getClass()).withIdentity(id+JOB_SUFFIX).build();
         TriggerBuilder<Trigger> builder = newTrigger().withIdentity(id+TRIGGER_SUFFIX);
         if (job.isStartNow()) builder = builder.startNow();
         final CronScheduleBuilder cronSchedule = cronSchedule(job.getCronTimeString());
         final Trigger trigger = builder.withSchedule(timeZone != null ? cronSchedule.inTimeZone(timeZone) : cronSchedule).build();
         scheduler.scheduleJob(jobDetail, trigger);
     }