kkkkkkkobzillla-utils: org.cobbzilla.util.string.Base64.OutputStream.write
write() [1/2]
void org.cobbzilla.util.string.Base64.OutputStream.write (int theByte) throws java.io.IOException
Writes the byte to the output stream after converting to/from Base64 notation.
When encoding, bytes are buffered three at a time before the output stream actually gets a write() call. When decoding, bytes are buffered four at a time.
Parameters
theByte the byte to write
Since
1.3
Definition at line 1933 of file Base64.java.
References org.cobbzilla.util.string.Base64.decode4to3(), and org.cobbzilla.util.string.Base64.encode3to4().
Referenced by org.cobbzilla.util.string.Base64.decodeToFile(), org.cobbzilla.util.string.Base64.encodeBytesToBytes(), and org.cobbzilla.util.string.Base64.encodeToFile().
{
             // Encoding suspended?
             if( suspendEncoding ) {
                 this.out.write( theByte );
                 return;
             }   // end if: supsended
             // Encode?
             if( encode ) {
                 buffer[ position++ ] = (byte)theByte;
                 if( position >= bufferLength ) { // Enough to encode.
                     this.out.write( encode3to4( b4, buffer, bufferLength, options ) );
                     lineLength += 4;
                     if( breakLines && lineLength >= MAX_LINE_LENGTH ) {
                         this.out.write( NEW_LINE );
                         lineLength = 0;
                     }   // end if: end of line
                     position = 0;
                 }   // end if: enough to output
             }   // end if: encoding
             // Else, Decoding
             else {
                 // Meaningful Base64 character?
                 if( decodabet[ theByte & 0x7f ] > WHITE_SPACE_ENC ) {
                     buffer[ position++ ] = (byte)theByte;
                     if( position >= bufferLength ) { // Enough to output.
                         int len = Base64.decode4to3( buffer, 0, b4, 0, options );
                         out.write( b4, 0, len );
                         position = 0;
                     }   // end if: enough to output
                 }   // end if: meaningful base64 character
                 else if( decodabet[ theByte & 0x7f ] != WHITE_SPACE_ENC ) {
                     throw new java.io.IOException( "Invalid character in Base64 data." );
                 }   // end else: not white space either
             }   // end else: decoding
         }   // end write