kkkkkkkobzillla-utils: org.cobbzilla.util.string.Base64.decode4to3
decode4to3()
static int org.cobbzilla.util.string.Base64.decode4to3 (byte [] source, int srcOffset, byte [] destination, int destOffset, int options) static private
Decodes four bytes from array source and writes the resulting bytes (up to three of them) to destination.
The source and destination arrays can be manipulated anywhere along their length by specifying srcOffset and destOffset. This method does not check to make sure your arrays are large enough to accomodate srcOffset + 4 for the source array or destOffset + 3 for the destination array. This method returns the actual number of bytes that were converted from the Base64 encoding.
This is the lowest level of the decoding methods with all possible parameters.
Parameters
source the array to convert
srcOffset the index where conversion begins
destination the array to hold the conversion
destOffset the index where output will be put
options alphabet type is pulled from this (standard, url-safe, ordered)
Returns
the number of decoded bytes converted
Exceptions
NullPointerException if source or destination arrays are null
IllegalArgumentException if srcOffset or destOffset are invalid or there is not enough room in the array.
Since
1.3
Definition at line 1030 of file Base64.java.
References org.cobbzilla.util.string.Base64.getDecodabet().
Referenced by org.cobbzilla.util.string.Base64.decode(), org.cobbzilla.util.string.Base64.InputStream.read(), and org.cobbzilla.util.string.Base64.OutputStream.write().
{
         // Lots of error checking and exception throwing
         if( source == null ){
             throw new NullPointerException( "Source array was null." );
         }   // end if
         if( destination == null ){
             throw new NullPointerException( "Destination array was null." );
         }   // end if
         if( srcOffset < 0 || srcOffset + 3 >= source.length ){
             throw new IllegalArgumentException( String.format(
                     "Source array with length %d cannot have offset of %d and still process four bytes.", source.length, srcOffset ) );
         }   // end if
         if( destOffset < 0 || destOffset +2 >= destination.length ){
             throw new IllegalArgumentException( String.format(
                     "Destination array with length %d cannot have offset of %d and still store three bytes.", destination.length, destOffset ) );
         }   // end if
         byte[] DECODABET = getDecodabet( options );
         // Example: Dk==
         if( source[ srcOffset + 2] == EQUALS_SIGN ) {
             // Two ways to do the same thing. Don't know which way I like best.
             //int outBuff =   ( ( DECODABET[ source[ srcOffset    ] ] << 24 ) >>>  6 )
             //              | ( ( DECODABET[ source[ srcOffset + 1] ] << 24 ) >>> 12 );
             int outBuff =   ( ( DECODABET[ source[ srcOffset    ] ] & 0xFF ) << 18 )
                     | ( ( DECODABET[ source[ srcOffset + 1] ] & 0xFF ) << 12 );
             destination[ destOffset ] = (byte)( outBuff >>> 16 );
             return 1;
         }
         // Example: DkL=
         else if( source[ srcOffset + 3 ] == EQUALS_SIGN ) {
             // Two ways to do the same thing. Don't know which way I like best.
             //int outBuff =   ( ( DECODABET[ source[ srcOffset     ] ] << 24 ) >>>  6 )
             //              | ( ( DECODABET[ source[ srcOffset + 1 ] ] << 24 ) >>> 12 )
             //              | ( ( DECODABET[ source[ srcOffset + 2 ] ] << 24 ) >>> 18 );
             int outBuff =   ( ( DECODABET[ source[ srcOffset     ] ] & 0xFF ) << 18 )
                     | ( ( DECODABET[ source[ srcOffset + 1 ] ] & 0xFF ) << 12 )
                     | ( ( DECODABET[ source[ srcOffset + 2 ] ] & 0xFF ) <<  6 );
             destination[ destOffset     ] = (byte)( outBuff >>> 16 );
             destination[ destOffset + 1 ] = (byte)( outBuff >>>  8 );
             return 2;
         }
         // Example: DkLE
         else {
             // Two ways to do the same thing. Don't know which way I like best.
             //int outBuff =   ( ( DECODABET[ source[ srcOffset     ] ] << 24 ) >>>  6 )
             //              | ( ( DECODABET[ source[ srcOffset + 1 ] ] << 24 ) >>> 12 )
             //              | ( ( DECODABET[ source[ srcOffset + 2 ] ] << 24 ) >>> 18 )
             //              | ( ( DECODABET[ source[ srcOffset + 3 ] ] << 24 ) >>> 24 );
             int outBuff =   ( ( DECODABET[ source[ srcOffset     ] ] & 0xFF ) << 18 )
                     | ( ( DECODABET[ source[ srcOffset + 1 ] ] & 0xFF ) << 12 )
                     | ( ( DECODABET[ source[ srcOffset + 2 ] ] & 0xFF ) <<  6)
                     | ( ( DECODABET[ source[ srcOffset + 3 ] ] & 0xFF )      );
             destination[ destOffset     ] = (byte)( outBuff >> 16 );
             destination[ destOffset + 1 ] = (byte)( outBuff >>  8 );
             destination[ destOffset + 2 ] = (byte)( outBuff       );
             return 3;
         }
     }   // end decodeToBytes