kkkkkkkobzillla-utils: org.cobbzilla.util.string.Base64.encode3to4
encode3to4() [1/2]
static byte [] org.cobbzilla.util.string.Base64.encode3to4 (byte [] b4, byte [] threeBytes, int numSigBytes, int options) static private
Encodes up to the first three bytes of array threeBytes and returns a four-byte array in Base64 notation.
The actual number of significant bytes in your array is given by numSigBytes. The array threeBytes needs only be as big as numSigBytes. Code can reuse a byte array by passing a four-byte array as b4.
Parameters
b4 A reusable byte array to reduce array instantiation
threeBytes the array to convert
numSigBytes the number of significant bytes in your array
Returns
four byte array in Base64 notation.
Since
1.5.1
Definition at line 466 of file Base64.java.
Referenced by org.cobbzilla.util.string.Base64.encode(), org.cobbzilla.util.string.Base64.encodeBytesToBytes(), org.cobbzilla.util.string.Base64.OutputStream.flushBase64(), org.cobbzilla.util.string.Base64.InputStream.read(), and org.cobbzilla.util.string.Base64.OutputStream.write().
{
         encode3to4( threeBytes, 0, numSigBytes, b4, 0, options );
         return b4;
     }   // end encode3to4