kkkkkkkobzillla-utils: org.cobbzilla.util.string.Base64.encodeBytes
encodeBytes() [1/4]
static String org.cobbzilla.util.string.Base64.encodeBytes (byte [] source) static
Encodes a byte array into Base64 notation.
Does not GZip-compress data.
Parameters
source The data to convert
Returns
The data in Base64-encoded form
Exceptions
NullPointerException if source array is null
Since
1.4
Definition at line 714 of file Base64.java.
Referenced by org.cobbzilla.util.string.Base64.encodeBytes(), org.cobbzilla.util.security.ShaUtil.sha256_base64(), org.cobbzilla.util.security.ShaUtil.sha256_filename(), and org.cobbzilla.util.security.CryptoUtil.string_encrypt().
{
         // Since we're not going to have the GZIP encoding turned on,
         // we're not going to have an java.io.IOException thrown, so
         // we should not force the user to have to catch it.
         String encoded = null;
         try {
             encoded = encodeBytes(source, 0, source.length, NO_OPTIONS);
         } catch (java.io.IOException ex) {
             assert false : ex.getMessage();
         }   // end catch
         assert encoded != null;
         return encoded;
     }   // end encodeBytes