kkkkkkkobzillla-utils: org.cobbzilla.util.string.Base64.decode
decode() [1/4]
static byte [] org.cobbzilla.util.string.Base64.decode (byte [] source) throws java.io.IOException static
Low-level access to decoding ASCII characters in the form of a byte array.
Ignores GUNZIP option, if it's set. This is not generally a recommended method, although it is used internally as part of the decoding process. Special case: if len = 0, an empty array is returned. Still, if you need more speed and reduced memory footprint (and aren't gzipping), consider this method.
Parameters
source The Base64 encoded data
Returns
decoded data
Since
2.3.1
Definition at line 1118 of file Base64.java.
References org.cobbzilla.util.string.Base64.NO_OPTIONS.
Referenced by org.cobbzilla.util.string.Base64.decode(), org.cobbzilla.util.string.Base64.decodeToObject(), and org.cobbzilla.util.security.CryptoUtil.string_decrypt().
{
         byte[] decoded = null;
 //        try {
         decoded = decode( source, 0, source.length, Base64.NO_OPTIONS );
 //        } catch( java.io.IOException ex ) {
 //            assert false : "IOExceptions only come from GZipping, which is turned off: " + ex.getMessage();
 //        }
         return decoded;
     }