kkkkkkkobzillla-utils: org.cobbzilla.util.string.Base64.getDecodabet
getDecodabet()
static final byte [] org.cobbzilla.util.string.Base64.getDecodabet (int options) static private
Returns one of the _SOMETHING_DECODABET byte arrays depending on the options specified.
It's possible, though silly, to specify ORDERED and URL_SAFE in which case one of them will be picked, though there is no guarantee as to which one will be picked.
Definition at line 430 of file Base64.java.
References org.cobbzilla.util.string.Base64._ORDERED_DECODABET, org.cobbzilla.util.string.Base64._STANDARD_DECODABET, and org.cobbzilla.util.string.Base64._URL_SAFE_DECODABET.
Referenced by org.cobbzilla.util.string.Base64.decode(), org.cobbzilla.util.string.Base64.decode4to3(), org.cobbzilla.util.string.Base64.InputStream.InputStream(), and org.cobbzilla.util.string.Base64.OutputStream.OutputStream().
{
         if( (options & URL_SAFE) == URL_SAFE) {
             return _URL_SAFE_DECODABET;
         } else if ((options & ORDERED) == ORDERED) {
             return _ORDERED_DECODABET;
         } else {
             return _STANDARD_DECODABET;
         }
     }   // end getAlphabet