kkkkkkkobzillla-utils: org.cobbzilla.util.json.JsonEdit.edit
edit()
String org.cobbzilla.util.json.JsonEdit.edit () throws Exception
Definition at line 40 of file JsonEdit.java.
References org.cobbzilla.util.json.JsonUtil.toString().
Referenced by org.cobbzilla.util.json.main.JsonEditor.run(), and org.cobbzilla.util.json.JsonEditTest.testEditJson().
{
         JsonNode root = readJson();
         for (JsonEditOperation operation : operations) {
             if (operation.isRead()) return JsonUtil.toString(findNode(root, operation.getPath()));
             root = apply(root, operation);
         }
         return JsonUtil.toString(JSON.treeToValue(root, Object.class));
     }