kkkkkkkobzillla-utils: org.cobbzilla.util.cache.AutoRefreshingReference.get
get()
T org.cobbzilla.util.cache.AutoRefreshingReference< T >.get ()
Definition at line 18 of file AutoRefreshingReference.java.
References org.cobbzilla.util.cache.AutoRefreshingReference< T >.getTimeout(), org.cobbzilla.util.cache.AutoRefreshingReference< T >.isEmpty(), org.cobbzilla.util.cache.AutoRefreshingReference< T >.object, and org.cobbzilla.util.cache.AutoRefreshingReference< T >.update().
                    {
         synchronized (object) {
             if (isEmpty() || now() - lastSet.get() > getTimeout()) update();
             return object.get();
         }
     }