kkkkkkkobzillla-utils: org.cobbzilla.util.daemon.Await.awaitAll
awaitAll() [2/2]
static <T> AwaitResult<T> org.cobbzilla.util.daemon.Await.awaitAll (Collection< Future<?>> futures, long timeout, ClockProvider clock) static
Definition at line 142 of file Await.java.
References org.cobbzilla.util.daemon.AwaitResult< T >.fail(), org.cobbzilla.util.time.ClockProvider.now(), org.cobbzilla.util.daemon.AwaitResult< T >.success(), and org.cobbzilla.util.daemon.AwaitResult< T >.timeout().
{
         long start = clock.now();
         final AwaitResult<T> result = new AwaitResult<>();
         final Collection<Future<?>> awaiting = new ArrayList<>(futures);
         while (clock.now() - start < timeout) {
             for (Iterator iter = awaiting.iterator(); iter.hasNext(); ) {
                 final Future f = (Future) iter.next();
                 if (f.isDone()) {
                     iter.remove();
                     try {
                         final T r = (T) f.get();
                         if (r != null) log.info("awaitAll: "+ r);
                         result.success(f, r);
                     } catch (Exception e) {
                         log.warn("awaitAll: "+e, e);
                         result.fail(f, e);
                     }
                 }
             }
             if (awaiting.isEmpty()) break;
             sleep(200);
         }
         result.timeout(awaiting);
         return result;
     }