kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.copy
copy() [4/4]
static <T> int org.cobbzilla.util.reflect.ReflectionUtil.copy (T dest, T src, String [] fields, String [] exclude) static
Same as copy(dest, src) but only named fields are copied.
Parameters
dest destination object, or a Map<String, Object>
src source object
fields only fields with these names will be considered for copying
exclude fields with these names will NOT be considered for copying
<T> objects must share a type
Returns
count of fields copied
Definition at line 441 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.copyFromMap(), org.cobbzilla.util.reflect.ReflectionUtil.fieldName(), org.cobbzilla.util.reflect.ReflectionUtil.isIgnored(), and org.cobbzilla.util.reflect.ReflectionUtil.setterForGetter().
{
         int copyCount = 0;
         final boolean isMap = dest instanceof Map;
         try {
             if (src instanceof Map) copyFromMap(dest, (Map<String, Object>) src, exclude);
             checkGetter:
             for (Method getter : src.getClass().getMethods()) {
                 // only look for getters on the source object (methods with no arguments that have a return value)
                 final Class<?>[] types = getter.getParameterTypes();
                 if (types.length != 0) continue;
                 if (getter.getReturnType().equals(Void.class)) continue;;
                 // and it must be named appropriately
                 final String fieldName = fieldName(getter.getName());
                 if (fieldName == null || ArrayUtils.contains(exclude, fieldName)) continue;
                 // if specific fields were given, it must be one of those
                 if (fields != null && !ArrayUtils.contains(fields, fieldName)) continue;
                 // getter must not be marked @Transient
                 if (isIgnored(src, fieldName, getter)) continue;
                 // what would the setter be called?
                 final String setterName = setterForGetter(getter.getName());
                 if (setterName == null) continue;
                 // get the setter method on the destination object
                 Method setter = null;
                 if (!isMap) {
                     try {
                         setter = dest.getClass().getMethod(setterName, getter.getReturnType());
                     } catch (Exception e) {
                         log.debug("copy: setter not found: " + setterName);
                         continue;
                     }
                 }
                 // do not copy null fields (should this be configurable?)
                 final Object srcValue = getter.invoke(src);
                 if (srcValue == null) continue;
                 // does the dest have a getter? if so grab the current value
                 Object destValue = null;
                 try {
                     if (isMap) {
                         destValue = ((Map) dest).get(fieldName);
                     } else {
                         destValue = getter.invoke(dest);
                     }
                 } catch (Exception e) {
                     log.debug("copy: error calling getter on dest: "+e);
                 }
                 // copy the value from src to dest, if it's different
                 if (!srcValue.equals(destValue)) {
                     if (isMap) {
                         ((Map) dest).put(fieldName, srcValue);
                     } else {
                         setter.invoke(dest, srcValue);
                     }
                     copyCount++;
                 }
             }
         } catch (Exception e) {
             throw new IllegalArgumentException("Error copying "+dest.getClass().getSimpleName()+" from src="+src+": "+e, e);
         }
         return copyCount;
     }