kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.callerFrame
callerFrame()
static StackTraceElement org.cobbzilla.util.reflect.ReflectionUtil.callerFrame (String match) static
Definition at line 1004 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.caller().
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.caller(), org.cobbzilla.util.reflect.ReflectionUtil.callerClassName(), and org.cobbzilla.util.reflect.ReflectionUtil.callerMethodName().
{
         final StackTraceElement[] t = new Throwable().getStackTrace();
         if (t == null || t.length == 0) return null;
         for (StackTraceElement s : t) if (caller(s).contains(match)) return s;
         return null;
     }