kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.forName
forName()
static <T> Class<? extends T> org.cobbzilla.util.reflect.ReflectionUtil.forName (String clazz) static
Do a Class.forName and only throw unchecked exceptions.
Parameters
clazz full class name. May end in [] to indicate array class
<T> The class type
Returns
A Class<clazz> object
Definition at line 109 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.arrayClass().
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.arrayClass(), org.cobbzilla.util.reflect.ReflectionUtil.forNames(), org.cobbzilla.util.reflect.ReflectionUtil.getSimpleClass(), and org.cobbzilla.util.reflect.ReflectionUtil.instantiate().
{
         if (empty(clazz)) return (Class<? extends T>) Object.class;
         if (clazz.endsWith("[]")) return arrayClass(forName(clazz.substring(0, clazz.length()-2)));
         try {
             return (Class<? extends T>) Class.forName(clazz);
         } catch (Exception e) {
             return die("Class.forName("+clazz+") error: "+e, e);
         }
     }