kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.instantiate
instantiate() [1/4]
static <T> T org.cobbzilla.util.reflect.ReflectionUtil.instantiate (Class< T > clazz) static
Create an instance of a class, only throwing unchecked exceptions.
The class must have a default constructor.
Parameters
clazz we will instantiate an object of this type
<T> The class type
Returns
An Object that is an instance of Class<clazz> object
Definition at line 133 of file ReflectionUtil.java.
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.copy(), org.cobbzilla.util.cron.CronJob.getCommandInstance(), org.cobbzilla.util.reflect.ReflectionUtil.instantiate(), org.cobbzilla.util.reflect.ReflectionUtil.mirror(), and org.cobbzilla.util.reflect.ReflectionUtil.set().
{
         try {
             return clazz.newInstance();
         } catch (Exception e) {
             return die("Error instantiating "+clazz+": "+e, e);
         }
     }