kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.getSimpleClass
getSimpleClass()
static Class<?> org.cobbzilla.util.reflect.ReflectionUtil.getSimpleClass (Object argument) static
Definition at line 241 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.forName().
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.getSimpleClassName(), and org.cobbzilla.util.reflect.ReflectionUtil.instantiate().
{
         Class<?> argClass = argument.getClass();
         final int enhancePos = argClass.getName().indexOf("$$Enhance");
         if (enhancePos != -1) {
             argClass = forName(argClass.getName().substring(0, enhancePos));
         }
         return argClass;
     }