kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.invoke_set
invoke_set()
static void org.cobbzilla.util.reflect.ReflectionUtil.invoke_set (Object target, String token, Object value) static private
Definition at line 819 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.getAccessorMethodName(), org.cobbzilla.util.reflect.ReflectionUtil.getNullArgument(), and org.cobbzilla.util.reflect.ReflectionUtil.Accessor.set.
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.set().
{
         final String methodName = getAccessorMethodName(Accessor.set, token);
         if (value == null) {
             // try to find a single-arg method named methodName...
             Method found = null;
             for (Method m : target.getClass().getMethods()) {
                 if (m.getName().equals(methodName) && m.getParameterTypes().length == 1) {
                     if (found != null) {
                         die("invoke_set: value was null and multiple single-arg methods named " + methodName + " exist");
                     } else {
                         found = m;
                     }
                 }
             }
             if (found == null) die("invoke_set: no method " + methodName + " found on target: " + target);
             try {
                 found.invoke(target, new Object[] { getNullArgument(found.getParameterTypes()[0]) });
             } catch (Exception e) {
                 die("Error calling " + methodName + " on target: " + target + " - " + e);
             }
         } else {
             try {
                 MethodUtils.invokeMethod(target, methodName, value);
             } catch (Exception e) {
                 die("Error calling " + methodName + ": " + e);
             }
         }
     }