kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.copy
copy() [1/4]
static <T> T org.cobbzilla.util.reflect.ReflectionUtil.copy (T thing) static
Make a copy of the object, assuming its class has a copy constructor.
Parameters
thing The thing to copy
<T> Whatevs
Returns
A copy of the object, created using the thing's copy constructor
Definition at line 258 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.instantiate().
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.copy(), org.cobbzilla.util.collection.ListUtil.deepCopy(), org.cobbzilla.util.reflect.ReflectionUtil.mirror(), org.cobbzilla.util.reflect.ReflectionUtil.toMap(), and org.cobbzilla.util.io.JarTrimmer.trim().
 { return (T) instantiate(thing.getClass(), thing); }