kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.setNull
setNull()
static void org.cobbzilla.util.reflect.ReflectionUtil.setNull (Object object, String field, Class type) static
Definition at line 762 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.getTarget(), and org.cobbzilla.util.reflect.ReflectionUtil.invoke_set_null().
Referenced by org.cobbzilla.util.reflect.ReflectionUtil.scrubStrings(), org.cobbzilla.util.reflect.ReflectionUtil.set(), and org.cobbzilla.util.reflect.ReflectionUtilTest.testGetSet().
{
         final String[] tokens = field.split("\\.");
         Object target = getTarget(object, tokens);
         if (target != null) invoke_set_null(target, tokens[tokens.length - 1], type);
     }