kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.set
set() [2/2]
static void org.cobbzilla.util.reflect.ReflectionUtil.set (Object object, String field, Object value, Class<?> type) static
Call a setter with a hint as to what the type should be.
Parameters
object the object to call set(field) on
field the field name
value the value to set
Definition at line 749 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.getTarget(), org.cobbzilla.util.reflect.ReflectionUtil.instantiate(), org.cobbzilla.util.reflect.ReflectionUtil.invoke_set(), and org.cobbzilla.util.reflect.ReflectionUtil.setNull().
{
         if (type != null) {
             if (value == null) {
                 setNull(object, field, type);
                 return;
             }
             value = instantiate(type, value);
         }
         final String[] tokens = field.split("\\.");
         Object target = getTarget(object, tokens);
         if (target != null) invoke_set(target, tokens[tokens.length - 1], value);
     }