kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.get
get() [1/2]
static Object org.cobbzilla.util.reflect.ReflectionUtil.get (Object object, String field) static
Call a getter.
getXXX and isXXX will both be checked.
Parameters
object the object to call get(field) on
field the field name
Returns
the value of the field
Exceptions
IllegalArgumentException If no getter for the field exists
Definition at line 688 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.invoke_get().
Referenced by org.cobbzilla.util.reflect.FieldComparator< T, F extends Comparable< F >.compare(), org.cobbzilla.util.jdbc.TypedResultSetBean< T >.map(), org.cobbzilla.util.handlebars.HandlebarsUtil.registerUtilityHelpers(), org.cobbzilla.util.reflect.ReflectionUtilTest.testGetSet(), and org.cobbzilla.util.collection.FieldTransformer.transform().
{
         Object target = object;
         for (String token : field.split("\\.")) {
             if (target == null) return null;
             target = invoke_get(target, token);
         }
         return target;
     }