kkkkkkkobzillla-utils: org.cobbzilla.util.reflect.ReflectionUtil.copyFromMap
copyFromMap() [2/2]
static <T> T org.cobbzilla.util.reflect.ReflectionUtil.copyFromMap (T dest, Map< String, Object > src, String [] exclude) static
Definition at line 559 of file ReflectionUtil.java.
References org.cobbzilla.util.reflect.ReflectionUtil.copyFromMap(), org.cobbzilla.util.reflect.ReflectionUtil.getPrimitiveClass(), org.cobbzilla.util.reflect.ReflectionUtil.hasGetter(), and org.cobbzilla.util.reflect.ReflectionUtil.hasSetter().
{
         for (Map.Entry<String, Object> entry : src.entrySet()) {
             final String key = entry.getKey();
             if (exclude != null && ArrayUtils.contains(exclude, key)) continue;
             final Object value = entry.getValue();
             if (value != null && Map.class.isAssignableFrom(value.getClass())) {
                 if (hasGetter(dest, key)) {
                     Map m = (Map) value;
                     if (m.isEmpty()) continue;
                     if (m.keySet().iterator().next().getClass().equals(String.class)) {
                         copyFromMap(get(dest, key), (Map<String, Object>) m);
                     } else {
                         log.info("copyFromMap: not recursively copying Map (has non-String keys): " + key);
                     }
                 }
             } else {
                 if (Map.class.isAssignableFrom(dest.getClass())) {// || dest.getClass().getName().equals(HashMap.class.getName())) {
                     ((Map) dest).put(key, value);
                 } else {
                     if (hasSetter(dest, key, value.getClass())) {
                         set(dest, key, value);
                     } else {
                         final Class pc = getPrimitiveClass(value.getClass());
                         if (pc != null && hasSetter(dest, key, pc)) {
                             set(dest, key, value);
                         } else {
                             log.info("copyFromMap: skipping uncopyable property: "+key);
                         }
                     }
                 }
             }
         }
         return dest;
     }