kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.main.PdfMergeMain.run
run()
void org.cobbzilla.util.handlebars.main.PdfMergeMain.run () throws Exception protected
Definition at line 25 of file PdfMergeMain.java.
References org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.err(), org.cobbzilla.util.handlebars.main.PdfMergeOptions.getContext(), org.cobbzilla.util.handlebars.main.PdfMergeOptions.getInputStream(), org.cobbzilla.util.handlebars.main.PdfMergeOptions.hasOutfile(), org.cobbzilla.util.handlebars.PdfMerger.merge(), org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.options, org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.out(), org.cobbzilla.util.handlebars.PdfMerger.setErrorHandler(), and org.cobbzilla.util.string.StringUtil.toString().
{
         final PdfMergeOptions options = getOptions();
         final List<String> errors = new ArrayList<>();
         PdfMerger.setErrorHandler(new GeneralErrorHandler() {
             @Override public <T> T handleError(String message) { errors.add(message); return null; }
             @Override public <T> T handleError(String message, Exception e) { return handleError(message+": "+e.getClass().getSimpleName()+": "+e.getMessage()); }
             @Override public <T> T handleError(List<String> validationErrors) { errors.addAll(validationErrors); return null; }
         });
         @Cleanup final InputStream in = options.getInputStream();
         try {
             if (options.hasOutfile()) {
                 final File outfile = options.getOutfile();
                 PdfMerger.merge(in, outfile, options.getContext(), getHandlebars());
                 out(abs(outfile));
             } else {
                 final File output = PdfMerger.merge(in, options.getContext(), getHandlebars());
                 out(abs(output));
             }
         } catch (Exception e) {
             err("Unexpected exception merging PDF: "+e.getClass().getSimpleName()+": "+e.getMessage());
         }
         if (!empty(errors)) {
             err(errors.size()+" error"+(errors.size() > 1 ? "s" : "")+" found when merging PDF:\n"+ StringUtil.toString(errors, "\n"));
         }
     }