kkkkkkkobzillla-utils: org.cobbzilla.util.security.ShaUtil.sha256_file
sha256_file() [2/2]
static String org.cobbzilla.util.security.ShaUtil.sha256_file (File file) static
Definition at line 67 of file ShaUtil.java.
References org.cobbzilla.util.system.CommandResult.getExceptionString(), org.cobbzilla.util.system.CommandResult.isZeroExitStatus(), org.cobbzilla.util.security.ShaUtil.sha256_file_java(), and org.cobbzilla.util.security.ShaUtil.SHA256_FILE_USE_SHELL_THRESHHOLD.
{
         final CommandResult result;
         try {
             if (file.length() < SHA256_FILE_USE_SHELL_THRESHHOLD) return sha256_file_java(file);
             result = exec(new CommandLine("sha256sum").addArgument(abs(file), false));
             if (result.isZeroExitStatus()) return split(result.getStdout(), " ").get(0);
         } catch (Exception e) {
             // if we tried the shell command, it may have failed, try the pure java version
             if (file.length() > SHA256_FILE_USE_SHELL_THRESHHOLD) return sha256_file_java(file);
             return die("sha256sum_file: Error calculating sha256 on " + abs(file) + ": " + e);
         }
         return die("sha256sum_file: sha256sum "+abs(file)+" exited with status "+result.getExitStatus()+", stderr="+result.getStderr()+", exception="+result.getExceptionString());
     }