kkkkkkkobzillla-utils: org.cobbzilla.util.security.ShaUtil.getMessageDigest
getMessageDigest()
static MessageDigest org.cobbzilla.util.security.ShaUtil.getMessageDigest (InputStream input) throws NoSuchAlgorithmException, IOException, DigestException static
Definition at line 102 of file ShaUtil.java.
References org.cobbzilla.util.security.ShaUtil.md().
Referenced by org.cobbzilla.util.security.ShaUtil.sha256_file_java(), and org.cobbzilla.util.security.ShaUtil.sha256_url().
{
         final byte[] buf = new byte[4096];
         final MessageDigest md = md();
         while (true) {
             int read = input.read(buf, 0, buf.length);
             if (read == -1) break;
             md.update(buf, 0, read);
         }
         return md;
     }