kkkkkkkobzillla-utils: org.cobbzilla.util.security.ShaUtil.sha256
sha256() [1/2]
static byte [] org.cobbzilla.util.security.ShaUtil.sha256 (String data) static
Definition at line 30 of file ShaUtil.java.
References org.cobbzilla.util.string.StringUtil.UTF8.
Referenced by org.cobbzilla.util.security.CryptoUtil.sha256(), org.cobbzilla.util.security.ShaUtil.sha256_base64(), org.cobbzilla.util.security.ShaUtil.sha256_filename(), org.cobbzilla.util.security.ShaUtil.sha256_hex(), and org.cobbzilla.util.io.TarballTest.validateUnrolledTarball().
{
         try {
             return sha256(data.getBytes(StringUtil.UTF8));
         } catch (Exception e) {
             return die("sha256: bad data: "+e, e);
         }
     }