kkkkkkkobzillla-utils: org.cobbzilla.util.security.ShaUtil.sha256_url
sha256_url()
static String org.cobbzilla.util.security.ShaUtil.sha256_url (String urlString) throws Exception static
Definition at line 92 of file ShaUtil.java.
References org.cobbzilla.util.security.ShaUtil.getMessageDigest(), org.cobbzilla.util.security.ShaUtil.md(), and org.cobbzilla.util.string.StringUtil.tohex().
{
         final URL url = new URL(urlString);
         final URLConnection urlConnection = url.openConnection();
         @Cleanup final InputStream input = urlConnection.getInputStream();
         final MessageDigest md = getMessageDigest(input);
         return StringUtil.tohex(md.digest());
     }