kkkkkkkobzillla-utils: org.cobbzilla.util.http.main.HttpMain.run
run()
void org.cobbzilla.util.http.main.HttpMain.run () throws Exception protected
Definition at line 15 of file HttpMain.java.
References org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.die(), org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.err(), org.cobbzilla.util.http.HttpResponseBean.getEntityString(), org.cobbzilla.util.http.HttpUtil.getResponse(), org.cobbzilla.util.http.HttpResponseBean.isOk(), org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.out(), and org.cobbzilla.util.http.HttpResponseBean.toMap().
{
         final HttpRequestBean request = json(readStdin(), HttpRequestBean.class);
         if (request == null) die("nothing read from stdin");
         final HttpResponseBean response = HttpUtil.getResponse(request);
         if (response.isOk()) {
             out(response.getEntityString());
         } else {
             err(json(response.toMap()));
         }
     }