kkkkkkkobzillla-utils: org.cobbzilla.util.security.bcrypt.BCrypt.ekskey
ekskey()
void org.cobbzilla.util.security.bcrypt.BCrypt.ekskey (byte data[], byte key[]) private
Perform the "enhanced key schedule" step described by Provos and Mazieres in "A Future-Adaptable Password Scheme" http://www.openbsd.org/papers/bcrypt-paper.ps.
Parameters
data salt information
key password information
Definition at line 572 of file BCrypt.java.
References org.cobbzilla.util.security.bcrypt.BCrypt.encipher(), and org.cobbzilla.util.security.bcrypt.BCrypt.streamtoword().
Referenced by org.cobbzilla.util.security.bcrypt.BCrypt.crypt_raw().
{
         int i;
         int koffp[] = { 0 }, doffp[] = { 0 };
         int lr[] = { 0, 0 };
         int plen = P.length, slen = S.length;
         for (i = 0; i < plen; i++)
             P[i] = P[i] ^ streamtoword(key, koffp);
         for (i = 0; i < plen; i += 2) {
             lr[0] ^= streamtoword(data, doffp);
             lr[1] ^= streamtoword(data, doffp);
             encipher(lr, 0);
             P[i] = lr[0];
             P[i + 1] = lr[1];
         }
         for (i = 0; i < slen; i += 2) {
             lr[0] ^= streamtoword(data, doffp);
             lr[1] ^= streamtoword(data, doffp);
             encipher(lr, 0);
             S[i] = lr[0];
             S[i + 1] = lr[1];
         }
     }