kkkkkkkobzillla-utils: org.cobbzilla.util.security.MD5Util.md5hex
md5hex() [1/5]
static String org.cobbzilla.util.security.MD5Util.md5hex (Logger log, File file) throws IOException static
Definition at line 30 of file MD5Util.java.
References org.cobbzilla.util.string.StringUtil.tohex().
Referenced by org.cobbzilla.util.security.MD5Util.md5hex(), and org.cobbzilla.util.security.MD5Util.MD5InputStream.md5hex().
{
         int BUFSIZ = 4096;
         try (FileInputStream fin = new FileInputStream(file)) {
             MessageDigest md5 = MessageDigest.getInstance("MD5");
             BufferedInputStream in = new BufferedInputStream(fin);
             byte[] buf = new byte[BUFSIZ];
             int bytesRead = in.read(buf);
             while (bytesRead != -1) {
                 md5.update(buf, 0, bytesRead);
                 bytesRead = in.read(buf);
             }
             return StringUtil.tohex(md5.digest());
         } catch (NoSuchAlgorithmException e) {
             return die("Error calculating MD5: " + e);
         }
     }