kkkkkkkobzillla-utils: org.cobbzilla.util.io.Decompressors.unroll
unroll()
static TempDir org.cobbzilla.util.io.Decompressors.unroll (File infile) throws Exception static
Definition at line 16 of file Decompressors.java.
References org.cobbzilla.util.io.Decompressors.extract(), org.cobbzilla.util.io.Decompressors.isZipFile(), and org.cobbzilla.util.io.Tarball.unroll().
{
         if (isTarball(infile)) {
             return Tarball.unroll(infile);
         } else if (isZipFile(infile.getName())) {
             final TempDir tempDir = new TempDir();
             extract(infile, tempDir);
             return tempDir;
         } else {
             return die("unroll: unsupported file: "+infile);
         }
     }