kkkkkkkobzillla-utils: org.cobbzilla.util.io.Decompressors.extract
extract()
static void org.cobbzilla.util.io.Decompressors.extract (File zipfile, File outdir) throws IOException static
Definition at line 58 of file Decompressors.java.
References org.cobbzilla.util.io.Decompressors.dirpart(), org.cobbzilla.util.io.Decompressors.extractFile(), and org.cobbzilla.util.io.Decompressors.mkdirs().
Referenced by org.cobbzilla.util.io.Decompressors.unroll().
{
         @Cleanup final ZipInputStream zin = new ZipInputStream(new FileInputStream(zipfile));
         ZipEntry entry;
         String name, dir;
         while ((entry = zin.getNextEntry()) != null) {
             name = entry.getName();
             if (entry.isDirectory()) {
                 mkdirs(outdir,name);
                 continue;
             }
             /* this part is necessary because file entry can come before
              * directory entry where is file located
              * i.e.:
              *   /foo/foo.txt
              *   /foo/
              */
             dir = dirpart(name);
             if (dir != null) mkdirs(outdir,dir);
             extractFile(zin, outdir, name);
         }
     }