kkkkkkkobzillla-utils: org.cobbzilla.util.io.FileUtil.getDefaultTempDir
getDefaultTempDir()
static File org.cobbzilla.util.io.FileUtil.getDefaultTempDir () static
Definition at line 562 of file FileUtil.java.
References org.cobbzilla.util.io.FileUtil.mkdirOrDie().
Referenced by org.cobbzilla.util.io.FileUtil.temp(), and org.cobbzilla.util.io.FileUtil.toFile().
 { return mkdirOrDie(defaultTempDir); }