kkkkkkkobzillla-utils: org.cobbzilla.util.io.FileUtil.toStringOrDie
toStringOrDie() [2/2]
static String org.cobbzilla.util.io.FileUtil.toStringOrDie (File f) static
Definition at line 188 of file FileUtil.java.
References org.cobbzilla.util.io.FileUtil.abs(), org.cobbzilla.util.io.FileUtil.path(), and org.cobbzilla.util.io.FileUtil.toString().
{
         try {
             return toString(f);
         } catch (FileNotFoundException e) {
             log.warn("toStringOrDie: returning null; file not found: "+abs(f));
             return null;
         } catch (IOException e) {
             final String path = f == null ? "null" : abs(f);
             throw new IllegalArgumentException("Error reading file ("+ path +"): "+e, e);
         }
     }