kkkkkkkobzillla-utils: org.cobbzilla.util.io.FileUtil.toPropertiesOrDie
toPropertiesOrDie() [2/2]
static Properties org.cobbzilla.util.io.FileUtil.toPropertiesOrDie (File f) static private
Definition at line 225 of file FileUtil.java.
References org.cobbzilla.util.io.FileUtil.abs(), org.cobbzilla.util.io.FileUtil.path(), and org.cobbzilla.util.io.FileUtil.toProperties().
{
         try {
             return toProperties(f);
         } catch (IOException e) {
             final String path = f == null ? "null" : abs(f);
             throw new IllegalArgumentException("Error reading properties file ("+ path +"): "+e, e);
         }
     }