kkkkkkkobzillla-utils: org.cobbzilla.util.io.FileUtil.toFile
toFile() [1/6]
static File org.cobbzilla.util.io.FileUtil.toFile (List< String > lines) throws IOException static
Definition at line 174 of file FileUtil.java.
References org.cobbzilla.util.io.FileUtil.getDefaultTempDir(), and org.cobbzilla.util.io.FileUtil.temp().
Referenced by org.cobbzilla.util.json.JsonUtilTest.assertReplacementMade(), org.cobbzilla.util.io.FileUtil.bzip2(), org.cobbzilla.util.handlebars.Base64ImageInsertion.getImageFile(), org.cobbzilla.util.handlebars.WordDocxMerger.merge(), org.cobbzilla.util.json.main.JsonEditor.run(), org.cobbzilla.util.io.FileUtil.symlink(), org.cobbzilla.util.system.CommandShell.tempScript(), org.cobbzilla.util.io.FileUtil.toFile(), and org.cobbzilla.util.io.FileUtil.toFileOrDie().
{
         final File temp = File.createTempFile(FileUtil.class.getSimpleName()+".toFile", "tmp", getDefaultTempDir());
         try (BufferedWriter writer = new BufferedWriter(new FileWriter(temp))) {
             for (String line : lines) {
                 writer.write(line+"\n");
             }
         }
         return temp;
     }