kkkkkkkobzillla-utils: org.cobbzilla.util.time.ImprovedTimezone.initZone
initZone()
static ImprovedTimezone org.cobbzilla.util.time.ImprovedTimezone.initZone (String line) static private
Definition at line 137 of file ImprovedTimezone.java.
References org.cobbzilla.util.time.ImprovedTimezone.gmtOffset, org.cobbzilla.util.time.ImprovedTimezone.ImprovedTimezone(), and org.cobbzilla.util.time.ImprovedTimezone.isGMT().
Referenced by org.cobbzilla.util.time.ImprovedTimezone.init().
{
         try {
             final StringTokenizer st = new StringTokenizer(line, "|");
             int id = Integer.parseInt(st.nextToken());
             final String gmtOffset = st.nextToken();
             final String timezoneName = st.nextToken();
             final String displayName = st.nextToken();
             final String linuxName = st.hasMoreTokens() ? st.nextToken() : timezoneName;
             final TimeZone tz = TimeZone.getTimeZone(timezoneName);
             if (!gmtOffset.equals("GMT") && isGMT(tz)) {
                 String msg = "Error looking up timezone: " + timezoneName + ": got GMT, expected " + gmtOffset;
                 log.error(msg);
                 die(msg);
             }
             return new ImprovedTimezone(id, gmtOffset, tz, displayName, linuxName);
         } catch (Exception e) {
             return die("Error processing line: "+line+": "+e, e);
         }
     }