kkkkkkkobzillla-utils: org.cobbzilla.util.http.CookieJar.add
add()
void org.cobbzilla.util.http.CookieJar.add (HttpCookieBean cookie)
Definition at line 18 of file CookieJar.java.
References org.cobbzilla.util.http.HttpCookieBean.expired(), and org.cobbzilla.util.collection.CaseInsensitiveStringKeyMap< V >.put().
Referenced by org.cobbzilla.util.http.CookieJar.addCookie(), and org.cobbzilla.util.http.CookieJar.CookieJar().
{
         if (cookie.expired()) {
             remove(cookie.getName());
         } else {
             put(cookie.getName(), cookie);
         }
     }