kkkkkkkobzillla-utils: org.cobbzilla.util.http.HttpUtil.getResponse
getResponse() [3/3]
static HttpResponseBean org.cobbzilla.util.http.HttpUtil.getResponse (String urlString) throws IOException static
Definition at line 219 of file HttpUtil.java.
References org.cobbzilla.util.http.HttpResponseBean.addHeader(), org.cobbzilla.util.http.HttpResponseBean.getEntity(), and org.cobbzilla.util.http.HttpResponseBean.setEntity().
{
         final HttpResponseBean bean = new HttpResponseBean();
         @Cleanup final CloseableHttpClient client = HttpClients.createDefault();
         final HttpResponse response = client.execute(new HttpGet(urlString));
         for (Header header : response.getAllHeaders()) {
             bean.addHeader(header.getName(), header.getValue());
         }
         bean.setStatus(response.getStatusLine().getStatusCode());
         if (response.getEntity() != null) {
             final Header contentType = response.getEntity().getContentType();
             if (contentType != null) bean.setContentType(contentType.getValue());
             bean.setContentLength(response.getEntity().getContentLength());
             bean.setEntity(response.getEntity().getContent());
         }
         return bean;
     }