kkkkkkkobzillla-utils: org.cobbzilla.util.http.HttpUtil.initHttpRequest
initHttpRequest()
static HttpUriRequest org.cobbzilla.util.http.HttpUtil.initHttpRequest (HttpRequestBean requestBean) static
Definition at line 241 of file HttpUtil.java.
References org.cobbzilla.util.http.HttpMethods.DELETE, org.cobbzilla.util.http.HttpMethods.GET, org.cobbzilla.util.http.HttpRequestBean.hasData(), org.cobbzilla.util.http.HttpMethods.POST, org.cobbzilla.util.http.HttpMethods.PUT, and org.cobbzilla.util.http.HttpUtil.setData().
Referenced by org.cobbzilla.util.http.HttpUtil.getResponse().
{
         try {
             final HttpUriRequest request;
             switch (requestBean.getMethod()) {
                 case HttpMethods.GET:
                     request = new HttpGet(requestBean.getUri());
                     break;
                 case HttpMethods.POST:
                     request = new HttpPost(requestBean.getUri());
                     break;
                 case HttpMethods.PUT:
                     request = new HttpPut(requestBean.getUri());
                     break;
                 case HttpMethods.DELETE:
                     request = new HttpDelete(requestBean.getUri());
                     break;
                 default:
                     return die("Invalid request method: " + requestBean.getMethod());
             }
             if (requestBean.hasData() && request instanceof HttpEntityEnclosingRequestBase) {
                 setData(requestBean.getEntity(), (HttpEntityEnclosingRequestBase) request);
             }
             return request;
         } catch (UnsupportedEncodingException e) {
             return die("initHttpRequest: " + e, e);
         }
     }