kkkkkkkobzillla-utils: org.cobbzilla.util.http.HttpUtil.getStreamResponse
getStreamResponse()
static HttpResponseBean org.cobbzilla.util.http.HttpUtil.getStreamResponse (HttpRequestBean request) static
Definition at line 174 of file HttpUtil.java.
References org.cobbzilla.util.http.HttpUtil.addStreamHeader(), org.cobbzilla.util.http.HttpRequestBean.hasStream(), org.cobbzilla.util.http.HttpResponseBean.setEntity(), and org.cobbzilla.util.http.HttpRequestBean.withHeader().
Referenced by org.cobbzilla.util.http.HttpUtil.getResponse().
{
         if (!request.hasStream()) return die("getStreamResponse: request stream was not set");
         try {
             final String boundary = hexnow();
             request.withHeader(CONTENT_TYPE, "multipart/form-data; boundary=" + boundary);
             @Cleanup("disconnect") final HttpURLConnection connection = (HttpURLConnection) new URL(request.getUri()).openConnection();
             connection.setDoOutput(true);
             connection.setRequestMethod(request.getMethod());
             for (NameAndValue header : request.getHeaders()) {
                 connection.setRequestProperty(header.getName(), header.getValue());
             }
             @Cleanup final OutputStream output = connection.getOutputStream();
             final PrintWriter writer = new PrintWriter(new OutputStreamWriter(output, Charset.defaultCharset()), true);
             writer.append("--" + boundary).append(CRLF);
             final String filename = request.getEntity();
             addStreamHeader(writer, CONTENT_DISPOSITION, "form-data; name=\"file\"; filename=\""+ filename +"\"");
             addStreamHeader(writer, CONTENT_TYPE, contentType(filename));
             writer.append(CRLF).flush();
             IOUtils.copy(request.getEntityInputStream(), output);
             output.flush();
             writer.append(CRLF);
             writer.append("--").append(boundary).append("--").append(CRLF).flush();
             HttpResponseBean response = new HttpResponseBean()
                     .setStatus(connection.getResponseCode())
                     .setHttpHeaders(connection.getHeaderFields());
             try {
                 response.setEntity(connection.getInputStream());
             } catch (IOException ioe) {
                 response.setEntity(connection.getErrorStream());
             }
             return response;
         } catch (Exception e) {
             return die("getStreamResponse: "+e, e);
         }
     }