kkkkkkkobzillla-utils: org.cobbzilla.util.http.HttpUtil.getResponse
getResponse() [2/3]
static HttpResponseBean org.cobbzilla.util.http.HttpUtil.getResponse (HttpRequestBean requestBean, HttpClient client) throws IOException static
Definition at line 142 of file HttpUtil.java.
References org.cobbzilla.util.http.HttpResponseBean.addHeader(), org.cobbzilla.util.http.HttpResponseBean.getEntity(), org.cobbzilla.util.http.HttpUtil.getStreamResponse(), org.cobbzilla.util.http.HttpUtil.initHttpRequest(), and org.cobbzilla.util.http.HttpResponseBean.setEntity().
{
         if (requestBean.hasStream()) return getStreamResponse(requestBean);
         final HttpResponseBean bean = new HttpResponseBean();
         final HttpUriRequest request = initHttpRequest(requestBean);
         for (NameAndValue header : requestBean.getHeaders()) {
             request.setHeader(header.getName(), header.getValue());
         }
         final HttpResponse response = client.execute(request);
         for (Header header : response.getAllHeaders()) {
             bean.addHeader(header.getName(), header.getValue());
         }
         bean.setStatus(response.getStatusLine().getStatusCode());
         if (response.getStatusLine().getStatusCode() != NO_CONTENT) {
             bean.setContentLength(response.getEntity().getContentLength());
             final Header contentType = response.getEntity().getContentType();
             if (contentType != null) {
                 bean.setContentType(contentType.getValue());
             }
             @Cleanup final InputStream content = response.getEntity().getContent();
             bean.setEntity(content);
         }
         return bean;
     }