kkkkkkkobzillla-utils: org.cobbzilla.util.json.main.JsonEditor.run
run()
void org.cobbzilla.util.json.main.JsonEditor.run () throws Exception
Definition at line 14 of file JsonEditor.java.
References org.cobbzilla.util.json.JsonEdit.edit(), org.cobbzilla.util.json.main.JsonEditorOptions.getInputJson(), org.cobbzilla.util.json.main.JsonEditorOptions.hasOutfile(), org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.options, and org.cobbzilla.util.io.FileUtil.toFile().
{
         final JsonEditorOptions options = getOptions();
         JsonEdit edit = new JsonEdit()
                 .setJsonData(options.getInputJson())
                 .addOperation(new JsonEditOperation()
                         .setType(options.getOperationType())
                         .setPath(options.getPath())
                         .setJson(options.getValue()));
         final String json = edit.edit();
         if (options.hasOutfile()) {
             FileUtil.toFile(options.getOutfile(), json);
         } else {
             if (empty(json)) {
                 System.exit(1);
             } else {
                 System.out.print(json);
             }
         }
         System.exit(0);
     }