kkkkkkkobzillla-utils: org.cobbzilla.util.http.PhantomUtil.execJs
execJs()
PhantomJSHandle org.cobbzilla.util.http.PhantomUtil.execJs (String script)
Definition at line 26 of file PhantomUtil.java.
References org.cobbzilla.util.http.PhantomUtil.defaultDriver().
Referenced by org.cobbzilla.util.http.HtmlScreenCapture.capture(), and org.cobbzilla.util.http.PhantomUtil.loadPageAndExec().
{
         final PhantomJSDriver driver = defaultDriver();
         final PhantomJSHandle handle = new PhantomJSHandle(driver);
         driver.setErrorHandler(handle);
         driver.executePhantomJS(script);
         return handle;
     }