kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.PdfMerger.insertImage
insertImage()
static void org.cobbzilla.util.handlebars.PdfMerger.insertImage (PDDocument pdfDocument, Object insert, Class<? extends ImageInsertion > clazz) throws IOException static protected
Definition at line 167 of file PdfMerger.java.
References org.cobbzilla.util.handlebars.ImageInsertion.getImageFile(), org.cobbzilla.util.handlebars.ImageInsertion.init(), and org.cobbzilla.util.handlebars.PdfMerger.insertImageOnPage().
Referenced by org.cobbzilla.util.handlebars.PdfMerger.merge().
{
         final ImageInsertion insertion;
         if (insert instanceof ImageInsertion) {
             insertion = (ImageInsertion) insert;
         } else if (insert instanceof Map) {
             insertion = instantiate(clazz);
             insertion.init((Map<String, Object>) insert);
         } else {
             die("insertImage("+clazz.getSimpleName()+"): invalid object: "+insert);
             return;
         }
         // write image to temp file
         File imageTemp = null;
         try {
             imageTemp = insertion.getImageFile();
             if (imageTemp != null) {
                 // create PD image
                 final PDImageXObject image = PDImageXObject.createFromFile(abs(imageTemp), pdfDocument);
                 final PDPageTree pages = pdfDocument.getDocumentCatalog().getPages();
                 final float insertionHeight = insertion.getHeight();
                 if (insertion.isWatermark()) {
                     for (PDPage page : pages) {
                         // set x, y, width and height to center insertion and maximize size on page
                         final float y = (page.getBBox().getHeight()/2.0f) - insertionHeight;
                         insertion.setX(20)
                                 .setY(y)
                                 .setWidth(page.getBBox().getWidth()-20)
                                 .setHeight(page.getBBox().getHeight()-10);
                         insertImageOnPage(image, insertion, pdfDocument, page);
                     }
                 } else {
                     insertImageOnPage(image, insertion, pdfDocument, pages.get(insertion.getPage()));
                 }
             }
         } finally {
             if (imageTemp != null && !imageTemp.delete()) log.warn("insertImage("+clazz.getSimpleName()+"): error deleting image file: "+abs(imageTemp));
         }
     }