kkkkkkkobzillla-utils: org.cobbzilla.util.collection.multi.MultiResult.toString
toString()
String org.cobbzilla.util.collection.multi.MultiResult.toString ()
Definition at line 23 of file MultiResult.java.
References org.cobbzilla.util.collection.multi.MultiResult.fail(), org.cobbzilla.util.collection.multi.MultiResult.failCount(), org.cobbzilla.util.collection.multi.MultiResult.getHeader(), and org.cobbzilla.util.collection.multi.MultiResult.successCount().
{
         final StringBuilder b = new StringBuilder();
         b.append("\n\n").append(getHeader()).append("\n--------------------\n")
                 .append(successCount()).append("\tsucceeded\n")
                 .append(failCount()).append("\tfailed");
         if (!failures.isEmpty()) {
             b.append(":\n");
             for (String fail : failures.keySet()) {
                 b.append(fail).append("\n");
             }
             b.append("--------------------\n");
             b.append("\nfailure details:\n");
             for (Map.Entry<String, String> fail : failures.entrySet()) {
                 b.append(fail.getKey()).append(":\t").append(fail.getValue()).append("\n");
                 b.append("--------\n");
             }
         } else {
             b.append("\n");
         }
         b.append("--------------------\n");
         return b.toString();
     }