kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.main.PdfConcatMain.run
run()
void org.cobbzilla.util.handlebars.main.PdfConcatMain.run () throws Exception protected
Definition at line 13 of file PdfConcatMain.java.
References org.cobbzilla.util.handlebars.PdfMerger.concatenate(), org.cobbzilla.util.handlebars.main.PdfConcatOptions.getOut(), org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.options, and org.cobbzilla.util.main.BaseMain< OPT extends BaseMainOptions >.out().
{
         final PdfConcatOptions options = getOptions();
         @Cleanup final OutputStream out = options.getOut();
         PdfMerger.concatenate(options.getInfiles(), out, options.getMaxMemory(), options.getMaxDisk());
         out("success");
     }