kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.HandlebarsUtil.apply
apply() [1/4]
static Map<String, Object> org.cobbzilla.util.handlebars.HandlebarsUtil.apply (Handlebars handlebars, Map< String, Object > map, Map< String, Object > ctx) static
Definition at line 76 of file HandlebarsUtil.java.
Referenced by org.cobbzilla.util.handlebars.HandlebarsUtil.apply(), org.cobbzilla.util.handlebars.HandlebarsUtil.applyReflectively(), org.cobbzilla.util.handlebars.HandlebarsUtil.getEmailRecipient(), org.cobbzilla.util.handlebars.WordDocxMerger.merge(), org.cobbzilla.util.handlebars.HandlebarsUtil.registerDateHelpers(), org.cobbzilla.util.handlebars.HandlebarsUtil.registerUtilityHelpers(), and org.cobbzilla.util.handlebars.PdfMerger.safeApply().
{
         return apply(handlebars, map, ctx, HB_START_CHAR, HB_END_CHAR);
     }