kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.HandlebarsUtil.applyReflectively
applyReflectively() [2/2]
static <T> T org.cobbzilla.util.handlebars.HandlebarsUtil.applyReflectively (Handlebars handlebars, T thing, Map< String, Object > ctx, char altStart, char altEnd) static
Definition at line 167 of file HandlebarsUtil.java.
References org.cobbzilla.util.handlebars.HandlebarsUtil.apply(), org.cobbzilla.util.handlebars.HandlebarsUtil.applyReflectively(), org.cobbzilla.util.handlebars.HandlebarsUtil.canApplyReflectively(), and org.cobbzilla.util.reflect.ReflectionUtil.setterForGetter().
{
         for (Method getterCandidate : thing.getClass().getMethods()) {
             if (!getterCandidate.getName().startsWith("get")) continue;
             if (!canApplyReflectively(getterCandidate.getReturnType())) continue;
             final String setterName = ReflectionUtil.setterForGetter(getterCandidate.getName());
             for (Method setterCandidate : thing.getClass().getMethods()) {
                 if (!setterCandidate.getName().equals(setterName)
                         || setterCandidate.getParameterTypes().length != 1
                         || !setterCandidate.getParameterTypes()[0].isAssignableFrom(getterCandidate.getReturnType())) {
                     continue;
                 }
                 try {
                     final Object value = getterCandidate.invoke(thing, (Object[]) null);
                     if (value == null) break;
                     if (value instanceof String) {
                         if (value.toString().contains("" + altStart + altStart)) {
                             setterCandidate.invoke(thing, apply(handlebars, (String) value, ctx, altStart, altEnd));
                         }
                     } else if (value instanceof JsonNode) {
                         setterCandidate.invoke(thing, json(apply(handlebars, json(value), ctx, altStart, altEnd), JsonNode.class));
                     } else if (value instanceof Map) {
                         setterCandidate.invoke(thing, apply(handlebars, (Map<String, Object>) value, ctx, altStart, altEnd));
 //                    } else if (Object[].class.isAssignableFrom(value.getClass())) {
 //                        final Object[] array = (Object[]) value;
 //                        final Object[] rendered = new Object[array.length];
 //                        for (int i=0; i<array.length; i++) {
 //                            rendered[i] = applyReflectively(handlebars, array[i], ctx, altStart, altEnd);
 //                        }
 //                        try {
 //                            setterCandidate.invoke(thing, rendered);
 //                        } catch (Exception e) {
 //                            die(e);
 //                        }
 //
                     } else {
                         // recurse
                         setterCandidate.invoke(thing, applyReflectively(handlebars, value, ctx, altStart, altEnd));
                     }
                 } catch (HandlebarsException e) {
                     throw e;
                 } catch (Exception e) {
                     // no setter for getter
                     log.warn("applyReflectively: " + e);
                 }
             }
         }
         return thing;
     }