kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.HandlebarsUtil.registerUtilityHelpers
registerUtilityHelpers()
static void org.cobbzilla.util.handlebars.HandlebarsUtil.registerUtilityHelpers (final Handlebars hb) static
Definition at line 248 of file HandlebarsUtil.java.
References org.cobbzilla.util.http.HttpContentTypes.APPLICATION_JSON, org.cobbzilla.util.handlebars.HandlebarsUtil.apply(), org.cobbzilla.util.handlebars.HandlebarsUtil.compare(), org.cobbzilla.util.handlebars.HandlebarsUtil.cval(), org.cobbzilla.util.handlebars.HandlebarsUtil.DEFAULT_FLOAT_FORMAT, org.cobbzilla.util.handlebars.HandlebarsUtil.EMPTY_SAFE_STRING, org.cobbzilla.util.string.LocaleUtil.fromString(), org.cobbzilla.util.reflect.ReflectionUtil.get(), org.cobbzilla.util.handlebars.HandlebarsUtil.getComparisonArgParam(), org.cobbzilla.util.handlebars.HandlebarsUtil.getIterator(), org.cobbzilla.util.handlebars.HandlebarsUtil.sendContext(), and org.cobbzilla.util.http.HttpContentTypes.TEXT_PLAIN.
{
         hb.registerHelper("exists", (src, options) -> empty(src) ? null : options.apply(options.fn));
         hb.registerHelper("not_exists", (src, options) -> !empty(src) ? null : options.apply(options.fn));
         hb.registerHelper("sha256", (src, options) -> {
             if (empty(src)) return "";
             src = apply(hb, src.toString(), (Map<String, Object>) options.context.model());
             src = sha256_hex(src.toString());
             return new Handlebars.SafeString(src.toString());
         });
         hb.registerHelper("format_float", (val, options) -> {
             if (empty(val)) return "";
             if (options.params.length > 2) return die("format_float: too many parameters. Usage: {{format_float expr [format] [locale]}}");
             final String format = options.params.length > 0 && !empty(options.param(0)) ? options.param(0) : DEFAULT_FLOAT_FORMAT;
             final Locale locale = LocaleUtil.fromString(options.params.length > 1 && !empty(options.param(1)) ? options.param(1) : null);
             val = apply(hb, val.toString(), (Map<String, Object>) options.context.model());
             val = String.format(locale, format, Double.valueOf(val.toString()));
             return new Handlebars.SafeString(val.toString());
         });
         hb.registerHelper("json", (src, options) -> {
             if (empty(src)) return "";
             return new Handlebars.SafeString(json(src));
         });
         hb.registerHelper("escaped_json", (src, options) -> {
             if (empty(src)) return "";
             return new Handlebars.SafeString(new String(JSON_STRING_ENCODER.quoteAsString(json(src))));
         });
         hb.registerHelper("context", (src, options) -> {
             if (empty(src)) return "";
             if (options.params.length > 0) return die("context: too many parameters. Usage: {{context [recipient]}}");
             final String ctxString = options.context.toString();
             final String recipient = src.toString();
             final String subject = options.params.length > 1 ? options.param(0) : null;
             sendContext(recipient, subject, ctxString,HttpContentTypes.TEXT_PLAIN);
             return new Handlebars.SafeString(ctxString);
         });
         hb.registerHelper("context_json", (src, options) -> {
             if (empty(src)) return "";
             try {
                 if (options.params.length > 0) return die("context: too many parameters. Usage: {{context [recipient]}}");
                 final String json = json(options.context.model());
                 final String recipient = src.toString();
                 final String subject = options.params.length > 1 ? options.param(0) : null;
                 sendContext(recipient, subject, json, HttpContentTypes.APPLICATION_JSON);
                 return new Handlebars.SafeString(json);
             } catch (Exception e) {
                 return new Handlebars.SafeString("Error calling json(options.context): "+e.getClass()+": "+e.getMessage());
             }
         });
         hb.registerHelper("required", (src, options) -> {
             if (src == null) throw new RequiredVariableUndefinedException("required: undefined variable");
             return new Handlebars.SafeString(src.toString());
         });
         hb.registerHelper("safe_name", (src, options) -> {
             if (empty(src)) return "";
             return new Handlebars.SafeString(safeSnakeName(src.toString()));
         });
         hb.registerHelper("urlEncode", (src, options) -> {
             if (empty(src)) return "";
             src = apply(hb, src.toString(), (Map<String, Object>) options.context.model());
             src = urlEncode(src.toString());
             return new Handlebars.SafeString(src.toString());
         });
         hb.registerHelper("lastElement", (thing, options) -> {
             if (thing == null) return null;
             final Iterator iter = getIterator(thing);
             final String path = options.param(0);
             Object lastElement = null;
             while (iter.hasNext()) {
                 lastElement = iter.next();
             }
             final Object val = ReflectionUtil.get(lastElement, path);
             if (val != null) return new Handlebars.SafeString(""+val);
             return EMPTY_SAFE_STRING;
         });
         hb.registerHelper("find", (thing, options) -> {
             if (thing == null) return null;
             final Iterator iter = getIterator(thing);
             final String path = options.param(0);
             final String arg = options.param(1);
             final String output = options.param(2);
             while (iter.hasNext()) {
                 final Object item = iter.next();
                 try {
                     final Object val = ReflectionUtil.get(item, path);
                     if (val != null && String.valueOf(val).equals(arg)) {
                         return new Handlebars.SafeString(""+ReflectionUtil.get(item, output));
                     }
                 } catch (Exception e) {
                     log.warn("find: "+e);
                 }
             }
             return EMPTY_SAFE_STRING;
         });
         hb.registerHelper("compare", (val1, options) -> {
             final String operator = options.param(0);
             final Object val2 = getComparisonArgParam(options);
             final Comparable v1 = cval(val1);
             final Object v2 = cval(val2);
             return (v1 == null && v2 == null) || (v1 != null && compare(operator, v1, v2)) ? options.fn(options) : options.inverse(options);
         });
         hb.registerHelper("string_compare", (val1, options) -> {
             final String operator = options.param(0);
             final Object val2 = getComparisonArgParam(options);
             final String v1 = val1 == null ? null : val1.toString();
             final String v2 = val2 == null ? null : val2.toString();
             return compare(operator, v1, v2) ? options.fn(options) : options.inverse(options);
         });
         hb.registerHelper("long_compare", (val1, options) -> {
             final String operator = options.param(0);
             final Object val2 = getComparisonArgParam(options);
             final Long v1 = val1 == null ? null : Long.valueOf(val1.toString());
             final Long v2 = val2 == null ? null : Long.valueOf(val2.toString());
             return compare(operator, v1, v2) ? options.fn(options) : options.inverse(options);
         });
         hb.registerHelper("double_compare", (val1, options) -> {
             final String operator = options.param(0);
             final Object val2 = getComparisonArgParam(options);
             final Double v1 = val1 == null ? null : Double.valueOf(val1.toString());
             final Double v2 = val2 == null ? null : Double.valueOf(val2.toString());
             return compare(operator, v1, v2) ? options.fn(options) : options.inverse(options);
         });
         hb.registerHelper("big_compare", (val1, options) -> {
             final String operator = options.param(0);
             final Object val2 = getComparisonArgParam(options);
             final BigDecimal v1 = val1 == null ? null : big(val1.toString());
             final BigDecimal v2 = val2 == null ? null : big(val2.toString());
             return compare(operator, v1, v2) ? options.fn(options) : options.inverse(options);
         });
         hb.registerHelper("expr", (val1, options) -> {
             final String operator = options.param(0);
             final String format = options.params.length > 2 ? options.param(2) : null;
             final Object val2 = getComparisonArgParam(options);
             final String v1 = val1.toString();
             final String v2 = val2.toString();
             final BigDecimal result;
             switch (operator) {
                 case "+": result = big(v1).add(big(v2)); break;
                 case "-": result = big(v1).subtract(big(v2)); break;
                 case "*": result = big(v1).multiply(big(v2)); break;
                 case "/": result = big(v1).divide(big(v2), MathContext.DECIMAL128); break;
                 case "%": result = big(v1).remainder(big(v2)).abs(); break;
                 case "^": result = big(v1).pow(big(v2).intValue()); break;
                 default: return die("expr: invalid operator: "+operator);
             }
             // can't use trigraph (?:) operator here, if we do then for some reason rval always ends up as a double
             final Number rval;
             if (v1.contains(".") || v2.contains(".") || operator.equals("/")) {
                 rval = result.doubleValue();
             } else {
                 rval = result.intValue();
             }
             if (format != null) {
                 final Locale locale = LocaleUtil.fromString(options.params.length > 3 && !empty(options.param(3)) ? options.param(3) : null);
                 return new Handlebars.SafeString(String.format(locale, format, rval));
             } else {
                 return new Handlebars.SafeString(rval.toString());
             }
         });
         hb.registerHelper("truncate", (Helper<Integer>) (max, options) -> {
             final String val = options.param(0, " ");
             if (empty(val)) return "";
             if (max == -1 || max >= val.length()) return val;
             return new Handlebars.SafeString(val.substring(0, max));
         });
         hb.registerHelper("truncate_and_url_encode", (Helper<Integer>) (max, options) -> {
             final String val = options.param(0, " ");
             if (empty(val)) return "";
             if (max == -1 || max >= val.length()) return simpleUrlEncode(val);
             return new Handlebars.SafeString(simpleUrlEncode(val.substring(0, max)));
         });
         hb.registerHelper("truncate_and_double_url_encode", (Helper<Integer>) (max, options) -> {
             final String val = options.param(0, " ");
             if (empty(val)) return "";
             if (max == -1 || max >= val.length()) return simpleUrlEncode(simpleUrlEncode(val));
             return new Handlebars.SafeString(simpleUrlEncode(simpleUrlEncode(val.substring(0, max))));
         });
         hb.registerHelper("length", (thing, options) -> {
             if (empty(thing)) return "0";
             if (thing.getClass().isArray()) return ""+((Object[]) thing).length;
             if (thing instanceof Collection) return ""+((Collection) thing).size();
             if (thing instanceof ArrayNode) return ""+((ArrayNode) thing).size();
             return "";
         });
         hb.registerHelper("first_nonempty", (thing, options) -> {
             if (!empty(thing)) return new Handlebars.SafeString(thing.toString());
             for (final Object param : options.params) {
                 if (!empty(param)) return new Handlebars.SafeString(param.toString());
             }
             return EMPTY_SAFE_STRING;
         });
     }