kkkkkkkobzillla-utils: org.cobbzilla.util.handlebars.HandlebarsUtil.registerDateHelpers
registerDateHelpers()
static void org.cobbzilla.util.handlebars.HandlebarsUtil.registerDateHelpers (Handlebars hb) static
Definition at line 612 of file HandlebarsUtil.java.
References org.cobbzilla.util.handlebars.HandlebarsUtil.apply(), org.cobbzilla.util.time.TimeUtil.DATE_FORMAT_MMDDYYYY, org.cobbzilla.util.time.TimeUtil.DATE_FORMAT_MMM_DD_YYYY, org.cobbzilla.util.time.TimeUtil.DATE_FORMAT_MMMM_D_YYYY, org.cobbzilla.util.time.TimeUtil.DATE_FORMAT_YYYY_MM_DD, org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.getTimeZone(), org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.print(), and org.cobbzilla.util.handlebars.HandlebarsUtil.DateHelper.zonedTimestamp().
{
         hb.registerHelper("date_format", new DateHelper() {
             public CharSequence apply(Object src, Options options) {
                 final DateTimeFormatter formatter = DateTimeFormat.forPattern(options.param(0));
                 return new Handlebars.SafeString(formatter.print(new DateTime(zonedTimestamp(src, options, 1),
                         getTimeZone(options, 1))));
             }
         });
         hb.registerHelper("date_short", new DateHelper() {
             public CharSequence apply(Object src, Options options) {
                 return print(TimeUtil.DATE_FORMAT_MMDDYYYY, src, options);
             }
         });
         hb.registerHelper("date_yyyy_mm_dd", new DateHelper() {
             public CharSequence apply(Object src, Options options) {
                 return print(TimeUtil.DATE_FORMAT_YYYY_MM_DD, src, options);
             }
         });
         hb.registerHelper("date_mmm_dd_yyyy", new DateHelper() {
             public CharSequence apply(Object src, Options options) {
                 return print(TimeUtil.DATE_FORMAT_MMM_DD_YYYY, src, options);
             }
         });
         hb.registerHelper("date_long", new DateHelper() {
             public CharSequence apply(Object src, Options options) {
                 return print(TimeUtil.DATE_FORMAT_MMMM_D_YYYY, src, options);
             }
         });
         hb.registerHelper("timestamp", new DateHelper() {
             public CharSequence apply(Object src, Options options) {
                 return new Handlebars.SafeString(Long.toString(zonedTimestamp(src, options)));
             }
         });
     }