kkkkkkkobzillla-utils: org.cobbzilla.util.bean.BeanMerger.merge
merge()
static void org.cobbzilla.util.bean.BeanMerger.merge (Object dest, Object orig, CopyEvaluator evaluator) static private
Definition at line 21 of file BeanMerger.java.
References org.cobbzilla.util.bean.BeanMerger.CopyEvaluator.shouldCopy().
Referenced by org.cobbzilla.util.bean.BeanMerger.mergeNotNullProperties(), and org.cobbzilla.util.bean.BeanMerger.mergeProperties().
{
         if (dest == null) throw new IllegalArgumentException ("No destination bean specified");
         if (orig == null) throw new IllegalArgumentException("No origin bean specified");
         PropertyDescriptor[] origDescriptors = propertyUtils.getPropertyDescriptors(orig);
         for (PropertyDescriptor origDescriptor : origDescriptors) {
             String name = origDescriptor.getName();
             if ("class".equals(name)) {
                 continue; // No point in trying to set an object's class
             }
             if (propertyUtils.isReadable(orig, name) &&
                     propertyUtils.isWriteable(dest, name)) {
                 try {
                     Object value = propertyUtils.getSimpleProperty(orig, name);
                     if (evaluator.shouldCopy(name, value)) {
                         propertyUtils.setProperty(dest, name, value);
                     }
                 } catch (NoSuchMethodException e) {
                     // Should not happen
                 } catch (Exception e) {
                     die("Error copying properties: " + e, e);
                 }
             }
         }
     }