kkkkkkkobzillla-utils: org.cobbzilla.util.javascript.JsEngine.evaluate
evaluate()
public<T> T org.cobbzilla.util.javascript.JsEngine.evaluate (String code, Map< String, Object > context) package
Definition at line 51 of file JsEngine.java.
References org.cobbzilla.util.javascript.JsEngine.availableScriptEngines, org.cobbzilla.util.javascript.JsEngine.getDefaultScript(), and org.cobbzilla.util.javascript.JsEngine.getNashorn().
Referenced by org.cobbzilla.util.string.StringUtil.diff(), org.cobbzilla.util.javascript.JsEngine.evaluateBoolean(), org.cobbzilla.util.javascript.JsEngine.evaluateInt(), org.cobbzilla.util.javascript.JsEngine.evaluateLong(), org.cobbzilla.util.javascript.JsEngine.evaluateString(), and org.cobbzilla.util.handlebars.HandlebarsUtil.registerJavaScriptHelper().
{
         ScriptEngine engine = null;
         final int numEngines;
         synchronized (availableScriptEngines) {
             numEngines = availableScriptEngines.size();
             if (numEngines > 0) {
                 engine = availableScriptEngines.remove(0);
             }
         }
         if (engine == null) {
             if (numEngines >= maxEngines) return die("evaluate("+code+"): maxEngines ("+maxEngines+") reached, no js engines available to execute, "+inUse.get()+" in use");
             engine = getNashorn();
         }
         inUse.incrementAndGet();
         try {
             final ScriptContext scriptContext = new SimpleScriptContext();
             final SimpleBindings bindings = new SimpleBindings();
             for (Map.Entry<String, Object> entry : context.entrySet()) {
                 final Object value = entry.getValue();
                 final Object wrappedOut;
                 Object[] wrappedArray = null;
                 if (value == null) {
                     wrappedOut = null;
                 } else if (value instanceof JsWrappable) {
                     wrappedOut = ((JsWrappable) value).jsObject();
                 } else if (value instanceof ArrayNode) {
                     wrappedOut = fromJsonOrDie((JsonNode) value, Object[].class);
                 } else if (value instanceof JsonNode) {
                     wrappedOut = fromJsonOrDie((JsonNode) value, Object.class);
                 } else if (value.getClass().isArray()) {
                     wrappedArray = (Object[]) value;
                     wrappedOut = null;
                 } else {
                     wrappedOut = value;
                 }
                 if (wrappedArray != null) {
                     bindings.put(entry.getKey(), wrappedArray);
                 } else {
                     bindings.put(entry.getKey(), wrappedOut);
                 }
             }
             scriptContext.setBindings(bindings, ScriptContext.ENGINE_SCOPE);
             try {
                 Object eval = engine.eval(getDefaultScript()+"\n"+code, scriptContext);
                 return (T) eval;
             } catch (ScriptException e) {
                 throw new IllegalStateException(e);
             }
         } finally {
             synchronized (availableScriptEngines) {
                 availableScriptEngines.add(engine);
             }
             inUse.decrementAndGet();
         }
     }