kkkkkkkobzillla-utils: org.cobbzilla.util.io.DamperedCompositeBufferedFilesystemWatcher.init
init()
void org.cobbzilla.util.io.DamperedCompositeBufferedFilesystemWatcher.init (long damperDuration, int maxEvents) protected
Definition at line 24 of file DamperedCompositeBufferedFilesystemWatcher.java.
References org.cobbzilla.util.io.DamperedCompositeBufferedFilesystemWatcher.buffer, org.cobbzilla.util.io.DamperedCompositeBufferedFilesystemWatcher.status(), and org.cobbzilla.util.io.DamperedCompositeBufferedFilesystemWatcher.uber_fire().
Referenced by org.cobbzilla.util.io.DamperedCompositeBufferedFilesystemWatcher.DamperedCompositeBufferedFilesystemWatcher().
{
         this.damper.set(damperDuration);
         this.buffer.set(new ArrayList<WatchEvent<?>>(maxEvents*10));
         this.damperThread.set(new Thread(new Runnable() {
             @Override public void run() {
                 log.debug(status()+" starting, sleeping for a while until there is some activity");
                 //noinspection InfiniteLoopStatement
                 while (true) {
                     if (!nap(TimeUnit.HOURS.toMillis(4), "waiting for filesystem watcher trigger to fire")) {
                         // we were interrupted. sleep for the damper time
                         while (!nap(damper.get())) {
                             // there was more activity, go back to sleep
                             log.debug(status()+" more activity while napping for damper, trying again");
                         }
                         // we successfully napped without being interrupted! fire the big trigger
                         log.debug(status()+": napped successfully, calling fire");
                         List<WatchEvent<?>> events;
                         synchronized (buffer) {
                             events = new ArrayList<>(buffer.get());
                             buffer.get().clear();
                         }
                         uber_fire(events);
                     }
                     log.debug(status()+" just fired, going back to sleep for a while until there is some more activity");
                 }
             }
         }));
         damperThread.get().setDaemon(true);
         damperThread.get().start();
     }